# 0825_peace_012_recall_aligned_model_comparison

동일 Recall 목표(0.95/0.97/0.99)에서 세 모델 전략의 FP/FCR을 비교하고, walk-forward 미래 구간과 final retrospective Test를 함께 정리합니다.

In [1]:

import gc
import hashlib
import json
import logging
import sys
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
import sklearn
import xgboost
from IPython.display import Markdown, display
from sklearn.compose import ColumnTransformer
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBClassifier

EXPERIMENT_ID = '0825_peace_012_recall_aligned_model_comparison'
RANDOM_STATE = 42
TARGET = 'class'
TIME_COLUMN = 'timestamp'
TYPE_COLUMN = 'inspection_type'
RECORD_ID = 'record_id'
DECISION_THRESHOLD = 0.5
TARGET_RECALLS = [0.95, 0.97, 0.99]
DIAGNOSTIC_TARGET = 0.97
TRAIN_END_FRACTION = 0.70
VALIDATION_END_FRACTION = 0.80
ENSEMBLE_CHECKPOINTS = [0.30, 0.40, 0.50, 0.70]
FOLD_MEMBER_CHECKPOINTS = {
    'fold_1': [0.30],
    'fold_2': [0.30, 0.40],
    'fold_3': [0.30, 0.40, 0.50],
}
FINAL_MEMBER_CHECKPOINTS = ENSEMBLE_CHECKPOINTS.copy()
WALK_FORWARD_SPECS = [
    {
        'fold': 'fold_1',
        'train_start': 0.00,
        'train_end': 0.30,
        'calibration_start': 0.30,
        'calibration_end': 0.40,
        'evaluation_start': 0.40,
        'evaluation_end': 0.50,
    },
    {
        'fold': 'fold_2',
        'train_start': 0.00,
        'train_end': 0.40,
        'calibration_start': 0.40,
        'calibration_end': 0.50,
        'evaluation_start': 0.50,
        'evaluation_end': 0.60,
    },
    {
        'fold': 'fold_3',
        'train_start': 0.00,
        'train_end': 0.50,
        'calibration_start': 0.50,
        'calibration_end': 0.60,
        'evaluation_start': 0.60,
        'evaluation_end': 0.70,
    },
]
XGB_PARAMS = {
    'objective': 'binary:logistic',
    'eval_metric': 'aucpr',
    'tree_method': 'hist',
    'n_estimators': 400,
    'learning_rate': 0.05,
    'max_depth': 5,
    'min_child_weight': 10,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'reg_alpha': 0.1,
    'reg_lambda': 5.0,
    'max_delta_step': 1.0,
    'random_state': RANDOM_STATE,
    'n_jobs': -1,
    'verbosity': 0,
}
MODEL_SPECS = [
    {
        'model_id': '003_004_single_unweighted',
        'label': '003/004 single type-expert',
        'kind': 'single',
        'use_class_weight': False,
    },
    {
        'model_id': '005_expanding_fold_ensemble',
        'label': '005 expanding checkpoint ensemble',
        'kind': 'ensemble',
        'use_class_weight': False,
    },
    {
        'model_id': '007_single_class_weight',
        'label': '007 single type-expert + scale_pos_weight',
        'kind': 'single',
        'use_class_weight': True,
    },
]

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 200)


def compute_scale_pos_weight(y: pd.Series) -> float:
    positive = int(y.sum())
    negative = int(len(y) - positive)
    if positive == 0 or negative == 0:
        raise ValueError('scale_pos_weight는 양성과 음성이 모두 있는 Train에서만 계산할 수 있습니다.')
    return negative / positive


def find_repo_root() -> Path:
    for candidate in [Path.cwd(), *Path.cwd().parents]:
        if (candidate / 'AGENTS.md').exists() and (candidate / 'notebooks').is_dir():
            return candidate.resolve()
    raise FileNotFoundError('AGENTS.md가 있는 저장소 루트를 찾지 못했습니다.')


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(chunk_size), b''):
            digest.update(chunk)
    return digest.hexdigest()


def find_data_pair(repo_root: Path) -> tuple[Path, Path]:
    candidates = [
        repo_root / 'data' / 'raw',
        repo_root.parent,
        Path.cwd(),
        Path.cwd().parent,
        Path.cwd().parent.parent,
    ]
    checked = set()
    for directory in candidates:
        resolved = directory.resolve()
        if resolved in checked:
            continue
        checked.add(resolved)
        data_path = resolved / 'dataset.csv'
        mapping_path = resolved / 'mapping.json'
        if data_path.exists() and mapping_path.exists():
            return data_path, mapping_path
    raise FileNotFoundError('dataset.csv와 mapping.json 쌍을 찾지 못했습니다.')


REPO_ROOT = find_repo_root()
DATA_PATH, MAPPING_PATH = find_data_pair(REPO_ROOT)
REPORT_PATH = REPO_ROOT / 'docs' / 'experiments' / f'{EXPERIMENT_ID}.md'
LOG_DIR = REPO_ROOT / 'docs' / 'peace'
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / f'{EXPERIMENT_ID}.log'

logger = logging.getLogger(EXPERIMENT_ID)
logger.setLevel(logging.INFO)
logger.handlers.clear()
formatter = logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
file_handler = logging.FileHandler(LOG_PATH, mode='w', encoding='utf-8')
file_handler.setFormatter(formatter)
stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setFormatter(formatter)
logger.addHandler(file_handler)
logger.addHandler(stream_handler)
logger.propagate = False

DATA_SHA256_BEFORE = sha256_file(DATA_PATH)
MAPPING_SHA256_BEFORE = sha256_file(MAPPING_PATH)
logger.info('experiment=%s', EXPERIMENT_ID)
logger.info('data_file=%s sha256=%s', DATA_PATH.name, DATA_SHA256_BEFORE)
logger.info('mapping_file=%s sha256=%s', MAPPING_PATH.name, MAPPING_SHA256_BEFORE)
logger.info(
    'versions python=%s pandas=%s sklearn=%s xgboost=%s',
    sys.version.split()[0],
    pd.__version__,
    sklearn.__version__,
    xgboost.__version__,
)
logger.info('target_recalls=%s diagnostic_target=%.2f', TARGET_RECALLS, DIAGNOSTIC_TARGET)
print('log saved to:', LOG_PATH.relative_to(REPO_ROOT))

raw_df = pd.read_csv(DATA_PATH, low_memory=False)
source_index_column = raw_df.columns[0]
if source_index_column.startswith('Unnamed:') or source_index_column == '':
    raw_df = raw_df.rename(columns={source_index_column: RECORD_ID})
elif source_index_column != RECORD_ID:
    raise ValueError(f'예상하지 못한 첫 번째 컬럼: {source_index_column}')

with MAPPING_PATH.open(encoding='utf-8') as stream:
    feature_mapping = json.load(stream)

required_columns = {RECORD_ID, TIME_COLUMN, TYPE_COLUMN, TARGET}
missing_required = required_columns - set(raw_df.columns)
assert not missing_required, f'필수 컬럼 누락: {sorted(missing_required)}'
assert len(raw_df) == 440_274
assert raw_df[RECORD_ID].is_unique
assert set(raw_df[TARGET].unique()) == {0, 1}
assert raw_df[TARGET].value_counts().to_dict() == {0: 435_652, 1: 4_622}
assert set(raw_df[TYPE_COLUMN].unique()) == {0, 1, 2, 3, 4}
assert set(feature_mapping) == {'0', '1', '2', '3', '4'}

raw_df[TIME_COLUMN] = pd.to_datetime(raw_df[TIME_COLUMN], errors='raise', utc=True)
raw_df = raw_df.sort_values([TIME_COLUMN, RECORD_ID], kind='stable').reset_index(drop=True)
inspection_columns = [column for column in raw_df.columns if column.startswith('inspection_feat')]
mapped_union = set().union(*(set(columns) for columns in feature_mapping.values()))
assert len(inspection_columns) == 70
assert len(mapped_union) == 65
assert mapped_union <= set(inspection_columns)

numeric_inputs = raw_df.select_dtypes(include=[np.number]).drop(columns=[TARGET, RECORD_ID])
assert np.isfinite(numeric_inputs.to_numpy()).all()

inspection_types = sorted(raw_df[TYPE_COLUMN].unique().tolist())
meta_columns = [column for column in raw_df.columns if column.startswith('meta_feat')]
feature_columns_by_type = {}
feature_rows = []
for inspection_type in inspection_types:
    mapped_columns = feature_mapping[str(inspection_type)]
    assert len(mapped_columns) == len(set(mapped_columns))
    assert set(mapped_columns) <= set(raw_df.columns)
    selected_columns = meta_columns + mapped_columns
    feature_columns_by_type[inspection_type] = selected_columns
    feature_rows.append(
        {
            'inspection_type': inspection_type,
            'meta_features': len(meta_columns),
            'mapped_inspection_features': len(mapped_columns),
            'raw_features_used': len(selected_columns),
        }
    )
feature_summary = pd.DataFrame(feature_rows).set_index('inspection_type')

data_summary = pd.Series(
    {
        'rows': len(raw_df),
        'columns': raw_df.shape[1],
        'false_call_0': int((raw_df[TARGET] == 0).sum()),
        'real_defect_1': int((raw_df[TARGET] == 1).sum()),
        'real_defect_rate_pct': raw_df[TARGET].mean() * 100,
        'inspection_types': raw_df[TYPE_COLUMN].nunique(),
        'inspection_features': len(inspection_columns),
        'mapped_feature_union': len(mapped_union),
        'timestamp_start': raw_df[TIME_COLUMN].min(),
        'timestamp_end': raw_df[TIME_COLUMN].max(),
    },
    name='raw_data',
)
display(data_summary)
display(feature_summary)
logger.info('data_verified rows=%d columns=%d class_0=%d class_1=%d', len(raw_df), raw_df.shape[1], int((raw_df[TARGET] == 0).sum()), int((raw_df[TARGET] == 1).sum()))

timestamp_group_sizes = raw_df.groupby(TIME_COLUMN, sort=True).size()
cumulative_rows = timestamp_group_sizes.cumsum().to_numpy()
timestamp_index = timestamp_group_sizes.index


def boundary_at(fraction: float):
    position = int(np.searchsorted(cumulative_rows, len(raw_df) * fraction, side='left'))
    return timestamp_index[position]


train_end_time = boundary_at(TRAIN_END_FRACTION)
validation_end_time = boundary_at(VALIDATION_END_FRACTION)
train_mask = raw_df[TIME_COLUMN] <= train_end_time
validation_mask = (raw_df[TIME_COLUMN] > train_end_time) & (raw_df[TIME_COLUMN] <= validation_end_time)
test_mask = raw_df[TIME_COLUMN] > validation_end_time

train_df = raw_df.loc[train_mask]
validation_df = raw_df.loc[validation_mask]
test_df = raw_df.loc[test_mask]
assert train_df[TIME_COLUMN].max() < validation_df[TIME_COLUMN].min()
assert validation_df[TIME_COLUMN].max() < test_df[TIME_COLUMN].min()
assert int(train_mask.sum() + validation_mask.sum() + test_mask.sum()) == len(raw_df)

split_summary = pd.DataFrame(
    [
        {
            'split': 'train',
            'rows': len(train_df),
            'positive_samples': int(train_df[TARGET].sum()),
            'positive_rate_pct': train_df[TARGET].mean() * 100,
            'timestamp_groups': train_df[TIME_COLUMN].nunique(),
            'start_time': train_df[TIME_COLUMN].min(),
            'end_time': train_df[TIME_COLUMN].max(),
        },
        {
            'split': 'validation',
            'rows': len(validation_df),
            'positive_samples': int(validation_df[TARGET].sum()),
            'positive_rate_pct': validation_df[TARGET].mean() * 100,
            'timestamp_groups': validation_df[TIME_COLUMN].nunique(),
            'start_time': validation_df[TIME_COLUMN].min(),
            'end_time': validation_df[TIME_COLUMN].max(),
        },
        {
            'split': 'test',
            'rows': len(test_df),
            'positive_samples': int(test_df[TARGET].sum()),
            'positive_rate_pct': test_df[TARGET].mean() * 100,
            'timestamp_groups': test_df[TIME_COLUMN].nunique(),
            'start_time': test_df[TIME_COLUMN].min(),
            'end_time': test_df[TIME_COLUMN].max(),
        },
    ]
).set_index('split')
display(split_summary)
logger.info('split_summary=%s', split_summary.reset_index().to_dict(orient='records'))

walk_forward_boundaries = {fraction: boundary_at(fraction) for fraction in [0.30, 0.40, 0.50, 0.60, 0.70]}
walk_forward_segments = {}
walk_forward_split_rows = []
for spec in WALK_FORWARD_SPECS:
    fold_name = spec['fold']
    train_end = walk_forward_boundaries[spec['train_end']]
    calibration_start = walk_forward_boundaries[spec['calibration_start']]
    calibration_end = walk_forward_boundaries[spec['calibration_end']]
    evaluation_start = walk_forward_boundaries[spec['evaluation_start']]
    evaluation_end = walk_forward_boundaries[spec['evaluation_end']]
    segments = {
        'train': raw_df.loc[raw_df[TIME_COLUMN] <= train_end],
        'calibration': raw_df.loc[(raw_df[TIME_COLUMN] > calibration_start) & (raw_df[TIME_COLUMN] <= calibration_end)],
        'evaluation': raw_df.loc[(raw_df[TIME_COLUMN] > evaluation_start) & (raw_df[TIME_COLUMN] <= evaluation_end)],
    }
    assert segments['train'][TIME_COLUMN].max() < segments['calibration'][TIME_COLUMN].min()
    assert segments['calibration'][TIME_COLUMN].max() < segments['evaluation'][TIME_COLUMN].min()
    walk_forward_segments[fold_name] = segments
    for segment_name, frame in segments.items():
        walk_forward_split_rows.append(
            {
                'fold': fold_name,
                'segment': segment_name,
                'rows': len(frame),
                'positive_samples': int(frame[TARGET].sum()),
                'positive_rate_pct': frame[TARGET].mean() * 100,
                'timestamp_groups': frame[TIME_COLUMN].nunique(),
                'start_time': frame[TIME_COLUMN].min(),
                'end_time': frame[TIME_COLUMN].max(),
            }
        )
walk_forward_split_summary = pd.DataFrame(walk_forward_split_rows).set_index(['fold', 'segment'])
display(walk_forward_split_summary)
logger.info('walk_forward_split_summary=%s', walk_forward_split_summary.reset_index().to_dict(orient='records'))


def evaluate_predictions(y_true, prediction, probability):
    y_true = np.asarray(y_true, dtype=np.int8)
    prediction = np.asarray(prediction, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)
    tn, fp, fn, tp = confusion_matrix(y_true, prediction, labels=[0, 1]).ravel()
    has_both_classes = np.unique(y_true).size == 2
    has_positive = (tp + fn) > 0
    return {
        'rows': len(y_true),
        'positive_samples': int(y_true.sum()),
        'tn': int(tn),
        'fp': int(fp),
        'fn': int(fn),
        'tp': int(tp),
        'accuracy': accuracy_score(y_true, prediction),
        'precision': precision_score(y_true, prediction, zero_division=0),
        'recall': recall_score(y_true, prediction, zero_division=0) if has_positive else np.nan,
        'false_call_reduction': tn / (tn + fp) if (tn + fp) else np.nan,
        'f1': f1_score(y_true, prediction, zero_division=0) if has_positive else np.nan,
        'roc_auc': roc_auc_score(y_true, probability) if has_both_classes else np.nan,
        'pr_auc': average_precision_score(y_true, probability) if has_both_classes else np.nan,
    }


def evaluate_probabilities(y_true, probability, threshold=DECISION_THRESHOLD):
    probability = np.asarray(probability, dtype=np.float64)
    prediction = (probability >= threshold).astype(np.int8)
    return evaluate_predictions(y_true, prediction, probability)


def select_threshold(y_true, probability, min_recall):
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)
    if np.unique(y_true).size != 2:
        raise ValueError('임계값 선택에는 positive와 negative가 모두 필요합니다.')
    order = np.argsort(-probability, kind='stable')
    sorted_probability = probability[order]
    sorted_target = y_true[order]
    cumulative_tp = np.cumsum(sorted_target == 1)
    cumulative_fp = np.cumsum(sorted_target == 0)
    group_ends = np.flatnonzero(np.r_[sorted_probability[:-1] != sorted_probability[1:], True])
    thresholds = sorted_probability[group_ends]
    tp = cumulative_tp[group_ends]
    fp = cumulative_fp[group_ends]
    total_positive = int((y_true == 1).sum())
    total_negative = int((y_true == 0).sum())
    recall = tp / total_positive
    false_call_reduction = 1.0 - (fp / total_negative)
    feasible = np.flatnonzero(recall >= min_recall)
    if feasible.size == 0:
        raise RuntimeError(f'Recall {min_recall:.2%} 조건을 만족하는 threshold가 없습니다.')
    best_local = np.lexsort((thresholds[feasible], recall[feasible], false_call_reduction[feasible]))[-1]
    best = feasible[best_local]
    selected_threshold = float(thresholds[best])
    metrics = evaluate_probabilities(y_true, probability, selected_threshold)
    return {'threshold': selected_threshold, 'min_recall': min_recall, **metrics}


_test_y = np.array([1, 0, 1, 0, 1, 0], dtype=np.int8)
_test_probability = np.array([0.9, 0.8, 0.7, 0.6, 0.4, 0.2])
_optimized = select_threshold(_test_y, _test_probability, min_recall=2 / 3)
_reference_rows = []
for _threshold in np.unique(_test_probability):
    _metrics = evaluate_probabilities(_test_y, _test_probability, _threshold)
    if _metrics['recall'] >= 2 / 3:
        _reference_rows.append((_metrics['false_call_reduction'], _metrics['recall'], _threshold))
_reference = max(_reference_rows)
assert np.isclose(_optimized['threshold'], _reference[2])
logger.info('threshold_selector_unit_test=PASS')


def make_preprocessor(feature_columns):
    categorical = [column for column in meta_columns if column in feature_columns]
    continuous = [column for column in feature_columns if column not in categorical]
    return ColumnTransformer(
        transformers=[
            ('categorical', OneHotEncoder(handle_unknown='ignore', dtype=np.float32), categorical),
            ('continuous', 'passthrough', continuous),
        ],
        sparse_threshold=1.0,
        verbose_feature_names_out=True,
    )


def predict_with_type_experts(train_frame, target_frames, use_class_weight, model_id, stage_name):
    prediction_map = {
        target_name: pd.Series(np.nan, index=frame.index, dtype='float64')
        for target_name, frame in target_frames.items()
    }
    training_rows = []
    for inspection_type in inspection_types:
        feature_columns = feature_columns_by_type[inspection_type]
        type_train = train_frame.loc[train_frame[TYPE_COLUMN] == inspection_type]
        y_train = type_train[TARGET].astype('int8')
        assert len(type_train) > 0
        assert y_train.nunique() == 2
        scale_pos_weight = compute_scale_pos_weight(y_train) if use_class_weight else 1.0
        logger.info(
            'fit_start model=%s stage=%s type=%d train_rows=%d train_positive=%d scale_pos_weight=%.6f',
            model_id,
            stage_name,
            inspection_type,
            len(type_train),
            int(y_train.sum()),
            scale_pos_weight,
        )
        preprocessor = make_preprocessor(feature_columns)
        X_train = preprocessor.fit_transform(type_train[feature_columns])
        model_params = XGB_PARAMS.copy()
        if use_class_weight:
            model_params['scale_pos_weight'] = scale_pos_weight
        model = XGBClassifier(**model_params)
        model.fit(X_train, y_train, verbose=False)
        for target_name, frame in target_frames.items():
            type_target = frame.loc[frame[TYPE_COLUMN] == inspection_type]
            assert len(type_target) > 0
            X_target = preprocessor.transform(type_target[feature_columns])
            probability = model.predict_proba(X_target)[:, 1]
            prediction_map[target_name].loc[type_target.index] = probability
            del X_target, probability
        training_rows.append(
            {
                'model_id': model_id,
                'stage': stage_name,
                'inspection_type': inspection_type,
                'train_rows': len(type_train),
                'train_positive': int(y_train.sum()),
                'raw_features': len(feature_columns),
                'encoded_features': X_train.shape[1],
                'scale_pos_weight': scale_pos_weight,
            }
        )
        logger.info('fit_done model=%s stage=%s type=%d', model_id, stage_name, inspection_type)
        del preprocessor, model, X_train
        gc.collect()
    for target_name, probability in prediction_map.items():
        assert probability.notna().all(), (model_id, stage_name, target_name)
    return prediction_map, training_rows


def evaluate_recall_target(model_id, model_label, fold_name, calibration_frame, calibration_probability, evaluation_frame, evaluation_probability, target_recall):
    selection = select_threshold(calibration_frame[TARGET], calibration_probability, min_recall=target_recall)
    future_metrics = evaluate_probabilities(evaluation_frame[TARGET], evaluation_probability, selection['threshold'])
    row = {
        'model_id': model_id,
        'model_label': model_label,
        'fold': fold_name,
        'target_recall': target_recall,
        'calibration_rows': int(selection['rows']),
        'calibration_positive_samples': int(selection['positive_samples']),
        'calibration_threshold': float(selection['threshold']),
        'calibration_recall': float(selection['recall']),
        'calibration_fp': int(selection['fp']),
        'calibration_fn': int(selection['fn']),
        'calibration_fcr': float(selection['false_call_reduction']),
        'future_rows': int(future_metrics['rows']),
        'future_positive_samples': int(future_metrics['positive_samples']),
        'future_recall': float(future_metrics['recall']),
        'future_fp': int(future_metrics['fp']),
        'future_fn': int(future_metrics['fn']),
        'future_fcr': float(future_metrics['false_call_reduction']),
        'future_precision': float(future_metrics['precision']),
        'future_pr_auc': float(future_metrics['pr_auc']),
        'future_tp': int(future_metrics['tp']),
        'future_tn': int(future_metrics['tn']),
    }
    prediction = (np.asarray(evaluation_probability) >= selection['threshold']).astype(np.int8)
    prediction_frame = pd.DataFrame(
        {
            RECORD_ID: evaluation_frame[RECORD_ID].to_numpy(),
            'fold': fold_name,
            'model_id': model_id,
            'target_recall': target_recall,
            'y_true': evaluation_frame[TARGET].astype('int8').to_numpy(),
            'probability': np.asarray(evaluation_probability, dtype=np.float64),
            'prediction': prediction,
        }
    )
    return row, prediction_frame


walk_probability_store = {}
training_history_rows = []
for spec in MODEL_SPECS:
    model_id = spec['model_id']
    walk_probability_store[model_id] = {}
    if spec['kind'] == 'single':
        for fold_spec in WALK_FORWARD_SPECS:
            fold_name = fold_spec['fold']
            segments = walk_forward_segments[fold_name]
            target_frames = {
                'calibration': segments['calibration'],
                'evaluation': segments['evaluation'],
            }
            prediction_map, training_rows = predict_with_type_experts(
                segments['train'],
                target_frames,
                use_class_weight=spec['use_class_weight'],
                model_id=model_id,
                stage_name=fold_name,
            )
            walk_probability_store[model_id][fold_name] = prediction_map
            training_history_rows.extend(training_rows)
    else:
        prediction_targets = {}
        for fold_spec in WALK_FORWARD_SPECS:
            fold_name = fold_spec['fold']
            prediction_targets[f'{fold_name}_calibration'] = walk_forward_segments[fold_name]['calibration']
            prediction_targets[f'{fold_name}_evaluation'] = walk_forward_segments[fold_name]['evaluation']
        checkpoint_predictions = {
            checkpoint: {
                target_name: pd.Series(np.nan, index=frame.index, dtype='float64')
                for target_name, frame in prediction_targets.items()
                if frame[TIME_COLUMN].min() > walk_forward_boundaries[checkpoint]
            }
            for checkpoint in ENSEMBLE_CHECKPOINTS
        }
        for checkpoint in ENSEMBLE_CHECKPOINTS:
            checkpoint_train = raw_df.loc[raw_df[TIME_COLUMN] <= walk_forward_boundaries[checkpoint]]
            target_frames = {name: prediction_targets[name] for name in checkpoint_predictions[checkpoint]}
            prediction_map, training_rows = predict_with_type_experts(
                checkpoint_train,
                target_frames,
                use_class_weight=False,
                model_id=model_id,
                stage_name=f'checkpoint_{checkpoint:.2f}',
            )
            checkpoint_predictions[checkpoint] = prediction_map
            training_history_rows.extend(training_rows)
        for fold_name, members in FOLD_MEMBER_CHECKPOINTS.items():
            calibration_name = f'{fold_name}_calibration'
            evaluation_name = f'{fold_name}_evaluation'
            calibration_probability = pd.Series(
                np.mean(np.vstack([checkpoint_predictions[checkpoint][calibration_name].to_numpy() for checkpoint in members]), axis=0),
                index=walk_forward_segments[fold_name]['calibration'].index,
                dtype='float64',
            )
            evaluation_probability = pd.Series(
                np.mean(np.vstack([checkpoint_predictions[checkpoint][evaluation_name].to_numpy() for checkpoint in members]), axis=0),
                index=walk_forward_segments[fold_name]['evaluation'].index,
                dtype='float64',
            )
            walk_probability_store[model_id][fold_name] = {
                'calibration': calibration_probability,
                'evaluation': evaluation_probability,
            }

walk_rows = []
walk_prediction_frames = []
for spec in MODEL_SPECS:
    model_id = spec['model_id']
    model_label = spec['label']
    for fold_spec in WALK_FORWARD_SPECS:
        fold_name = fold_spec['fold']
        segments = walk_forward_segments[fold_name]
        calibration_probability = walk_probability_store[model_id][fold_name]['calibration']
        evaluation_probability = walk_probability_store[model_id][fold_name]['evaluation']
        for target_recall in TARGET_RECALLS:
            row, prediction_frame = evaluate_recall_target(
                model_id,
                model_label,
                fold_name,
                segments['calibration'],
                calibration_probability,
                segments['evaluation'],
                evaluation_probability,
                target_recall,
            )
            walk_rows.append(row)
            if np.isclose(target_recall, DIAGNOSTIC_TARGET):
                walk_prediction_frames.append(prediction_frame)
        logger.info('walk_evaluated model=%s fold=%s', model_id, fold_name)

walk_results = pd.DataFrame(walk_rows).sort_values(['target_recall', 'model_id', 'fold']).reset_index(drop=True)
training_history = pd.DataFrame(training_history_rows)

def summarize_walk(group: pd.DataFrame) -> pd.Series:
    target_recall = float(group['target_recall'].iloc[0])
    return pd.Series(
        {
            'folds': int(group['fold'].nunique()),
            'mean_calibration_threshold': group['calibration_threshold'].mean(),
            'mean_future_recall': group['future_recall'].mean(),
            'min_future_recall': group['future_recall'].min(),
            'recall_target_hit_folds': int((group['future_recall'] >= target_recall).sum()),
            'mean_future_fp': group['future_fp'].mean(),
            'total_future_fp': int(group['future_fp'].sum()),
            'mean_future_fn': group['future_fn'].mean(),
            'mean_future_fcr': group['future_fcr'].mean(),
        }
    )

walk_summary = walk_results.groupby(['target_recall', 'model_id', 'model_label'], sort=True).apply(summarize_walk).reset_index()
walk_summary = walk_summary.sort_values(['target_recall', 'mean_future_fp', 'mean_future_fcr'], ascending=[True, True, False]).reset_index(drop=True)
display(walk_results)
display(walk_summary)
logger.info('walk_summary=%s', walk_summary.to_dict(orient='records'))

final_probability_store = {}
for spec in MODEL_SPECS:
    model_id = spec['model_id']
    if spec['kind'] == 'single':
        prediction_map, training_rows = predict_with_type_experts(
            train_df,
            {'validation': validation_df, 'test': test_df},
            use_class_weight=spec['use_class_weight'],
            model_id=model_id,
            stage_name='final_train70',
        )
        final_probability_store[model_id] = prediction_map
        training_history = pd.concat([training_history, pd.DataFrame(training_rows)], ignore_index=True)
    else:
        prediction_targets = {
            'final_validation': validation_df,
            'final_test': test_df,
        }
        checkpoint_predictions = {}
        for checkpoint in FINAL_MEMBER_CHECKPOINTS:
            checkpoint_train = raw_df.loc[raw_df[TIME_COLUMN] <= walk_forward_boundaries[checkpoint]]
            prediction_map, training_rows = predict_with_type_experts(
                checkpoint_train,
                prediction_targets,
                use_class_weight=False,
                model_id=model_id,
                stage_name=f'final_checkpoint_{checkpoint:.2f}',
            )
            checkpoint_predictions[checkpoint] = prediction_map
            training_history = pd.concat([training_history, pd.DataFrame(training_rows)], ignore_index=True)
        validation_probability = pd.Series(
            np.mean(np.vstack([checkpoint_predictions[checkpoint]['final_validation'].to_numpy() for checkpoint in FINAL_MEMBER_CHECKPOINTS]), axis=0),
            index=validation_df.index,
            dtype='float64',
        )
        test_probability = pd.Series(
            np.mean(np.vstack([checkpoint_predictions[checkpoint]['final_test'].to_numpy() for checkpoint in FINAL_MEMBER_CHECKPOINTS]), axis=0),
            index=test_df.index,
            dtype='float64',
        )
        final_probability_store[model_id] = {
            'validation': validation_probability,
            'test': test_probability,
        }

final_rows = []
for spec in MODEL_SPECS:
    model_id = spec['model_id']
    model_label = spec['label']
    validation_probability = final_probability_store[model_id]['validation']
    test_probability = final_probability_store[model_id]['test']
    for target_recall in TARGET_RECALLS:
        selection = select_threshold(validation_df[TARGET], validation_probability, min_recall=target_recall)
        test_metrics = evaluate_probabilities(test_df[TARGET], test_probability, selection['threshold'])
        final_rows.append(
            {
                'model_id': model_id,
                'model_label': model_label,
                'target_recall': target_recall,
                'validation_threshold': float(selection['threshold']),
                'validation_recall': float(selection['recall']),
                'validation_fp': int(selection['fp']),
                'validation_fcr': float(selection['false_call_reduction']),
                'test_recall': float(test_metrics['recall']),
                'test_fp': int(test_metrics['fp']),
                'test_fn': int(test_metrics['fn']),
                'test_fcr': float(test_metrics['false_call_reduction']),
                'test_precision': float(test_metrics['precision']),
                'test_pr_auc': float(test_metrics['pr_auc']),
                'test_tp': int(test_metrics['tp']),
                'test_tn': int(test_metrics['tn']),
                'selection_note': 'Test reused from prior experiments; threshold selected on validation only.',
            }
        )
final_results = pd.DataFrame(final_rows).sort_values(['target_recall', 'test_fp', 'test_fcr'], ascending=[True, True, False]).reset_index(drop=True)
display(final_results)
logger.info('final_results=%s', final_results.to_dict(orient='records'))

pooled_predictions = pd.concat(walk_prediction_frames, ignore_index=True)
diagnostic_rows = []
correlation_rows = []
for model_a, model_b in combinations([spec['model_id'] for spec in MODEL_SPECS], 2):
    pair = pooled_predictions.pivot_table(
        index=[RECORD_ID, 'fold', 'target_recall', 'y_true'],
        columns='model_id',
        values=['prediction', 'probability'],
    )
    pred_a = pair[('prediction', model_a)].astype('int8')
    pred_b = pair[('prediction', model_b)].astype('int8')
    prob_a = pair[('probability', model_a)].astype('float64')
    prob_b = pair[('probability', model_b)].astype('float64')
    y_true = pair.index.get_level_values('y_true').astype('int8')
    fn_a = (y_true == 1) & (pred_a == 0)
    fn_b = (y_true == 1) & (pred_b == 0)
    fp_a = (y_true == 0) & (pred_a == 1)
    fp_b = (y_true == 0) & (pred_b == 1)
    diagnostic_rows.append(
        {
            'target_recall': DIAGNOSTIC_TARGET,
            'model_a': model_a,
            'model_b': model_b,
            'disagreement_rate': float((pred_a != pred_b).mean()),
            'probability_corr': float(np.corrcoef(prob_a, prob_b)[0, 1]),
            'fn_a': int(fn_a.sum()),
            'fn_b': int(fn_b.sum()),
            'shared_fn': int((fn_a & fn_b).sum()),
            'fn_only_a': int((fn_a & ~fn_b).sum()),
            'fn_only_b': int((fn_b & ~fn_a).sum()),
            'fp_a': int(fp_a.sum()),
            'fp_b': int(fp_b.sum()),
            'shared_fp': int((fp_a & fp_b).sum()),
            'fp_only_a': int((fp_a & ~fp_b).sum()),
            'fp_only_b': int((fp_b & ~fp_a).sum()),
        }
    )

diagnostic_summary = pd.DataFrame(diagnostic_rows).sort_values(['model_a', 'model_b']).reset_index(drop=True)
display(diagnostic_summary)
logger.info('diagnostic_summary=%s', diagnostic_summary.to_dict(orient='records'))

DATA_SHA256_AFTER = sha256_file(DATA_PATH)
MAPPING_SHA256_AFTER = sha256_file(MAPPING_PATH)
assert DATA_SHA256_AFTER == DATA_SHA256_BEFORE
assert MAPPING_SHA256_AFTER == MAPPING_SHA256_BEFORE

verification = pd.Series(
    {
        'dataset_sha256_unchanged': True,
        'mapping_sha256_unchanged': True,
        'dataset_sha256': DATA_SHA256_BEFORE,
        'mapping_sha256': MAPPING_SHA256_BEFORE,
        'walk_rows': len(walk_results),
        'final_rows': len(final_results),
        'diagnostic_pairs': len(diagnostic_summary),
        'log_file': f'docs/peace/{LOG_PATH.name}',
        'report_file': f'docs/experiments/{REPORT_PATH.name}',
    },
    name='verification',
)
display(verification)
logger.info('source_integrity=PASS')

MODEL_LABELS = {spec['model_id']: spec['label'] for spec in MODEL_SPECS}


def pct(value: float) -> str:
    return f'{value * 100:.2f}%'


def md_table(df: pd.DataFrame, float_formats=None) -> str:
    if float_formats is None:
        float_formats = {}
    formatted = df.copy()
    for column, formatter in float_formats.items():
        if column in formatted.columns:
            formatted[column] = formatted[column].map(formatter)
    return formatted.to_markdown(index=False)


walk_report = walk_results[
    [
        'target_recall',
        'model_label',
        'fold',
        'calibration_threshold',
        'calibration_fp',
        'calibration_fcr',
        'future_recall',
        'future_fp',
        'future_fcr',
        'future_fn',
    ]
].rename(
    columns={
        'target_recall': 'target_recall',
        'model_label': 'model',
        'fold': 'fold',
        'calibration_threshold': 'calibration_threshold',
        'calibration_fp': 'calibration_fp',
        'calibration_fcr': 'calibration_fcr',
        'future_recall': 'future_recall',
        'future_fp': 'future_fp',
        'future_fcr': 'future_fcr',
        'future_fn': 'future_fn',
    }
)
walk_summary_report = walk_summary[
    [
        'target_recall',
        'model_label',
        'mean_future_recall',
        'min_future_recall',
        'recall_target_hit_folds',
        'mean_future_fp',
        'total_future_fp',
        'mean_future_fcr',
    ]
].rename(columns={'model_label': 'model'})
final_report = final_results[
    [
        'target_recall',
        'model_label',
        'validation_threshold',
        'validation_fp',
        'validation_fcr',
        'test_recall',
        'test_fp',
        'test_fcr',
        'test_fn',
        'selection_note',
    ]
].rename(columns={'model_label': 'model'})
diagnostic_report = diagnostic_summary.copy()
diagnostic_report['model_a'] = diagnostic_report['model_a'].map(MODEL_LABELS)
diagnostic_report['model_b'] = diagnostic_report['model_b'].map(MODEL_LABELS)

best_by_target = final_results.sort_values(['target_recall', 'test_fp', 'test_fcr'], ascending=[True, True, False]).groupby('target_recall', sort=True).first().reset_index()
conclusion_lines = []
for _, row in best_by_target.iterrows():
    conclusion_lines.append(
        f"- Target recall {row['target_recall']:.2f}: lowest Test FP came from {row['model_label']} at threshold {row['validation_threshold']:.6f} with Test recall {pct(row['test_recall'])}, FP {int(row['test_fp']):,}, FCR {pct(row['test_fcr'])}."
    )
ensemble_diag = diagnostic_summary[
    (diagnostic_summary['model_a'] == '005_expanding_fold_ensemble')
    | (diagnostic_summary['model_b'] == '005_expanding_fold_ensemble')
].copy()
if not ensemble_diag.empty:
    diag_line = ensemble_diag.sort_values('disagreement_rate', ascending=False).iloc[0]
    other_model = diag_line['model_b'] if diag_line['model_a'] == '005_expanding_fold_ensemble' else diag_line['model_a']
    conclusion_lines.append(
        f"- Ensemble diagnostic at target recall {DIAGNOSTIC_TARGET:.2f}: versus {MODEL_LABELS[other_model]}, disagreement was {pct(diag_line['disagreement_rate'])}, shared FN {int(diag_line['shared_fn'])}, ensemble-only FN {int(diag_line['fn_only_a'] if diag_line['model_a'] == '005_expanding_fold_ensemble' else diag_line['fn_only_b'])}, ensemble-only FP {int(diag_line['fp_only_a'] if diag_line['model_a'] == '005_expanding_fold_ensemble' else diag_line['fp_only_b'])}."
    )

report_text = "\n".join([
    f'# {EXPERIMENT_ID}',
    '',
    '## 연결된 노트북',
    '',
    f'`notebooks/{EXPERIMENT_ID}.ipynb`',
    '',
    '## 상태',
    '',
    '완료',
    '',
    '## 목적',
    '',
    '003/004 단일 type-expert, 005 expanding checkpoint ensemble, 007 type별 `scale_pos_weight` 모델을 동일한 분할·피처·XGBoost 파라미터에서 비교하고, 동일 Recall 목표에서 미래 Fold와 최종 Test의 FP/FCR 차이를 정리한다.',
    '',
    '## 설정',
    '',
    f'- Target recall: {TARGET_RECALLS}',
    f'- Walk-forward fold: 004/005와 동일한 expanding 3-fold',
    f'- Final benchmark: 0~70% Train / 70~80% Validation / 80~100% Test',
    f'- Threshold rule: 기존 `select_threshold` 로직 그대로 사용, calibration/validation에서 recall 제약을 만족하는 threshold 중 FCR 최대 선택',
    f'- Source integrity: dataset sha256 `{DATA_SHA256_BEFORE}`, mapping sha256 `{MAPPING_SHA256_BEFORE}`',
    f'- Log: `docs/peace/{LOG_PATH.name}`',
    '',
    '## 데이터 분할',
    '',
    split_summary.reset_index().to_markdown(index=False),
    '',
    '## Walk-forward 구성',
    '',
    walk_forward_split_summary.reset_index().to_markdown(index=False),
    '',
    '## Fold별 Recall-aligned 결과',
    '',
    md_table(
        walk_report,
        {
            'target_recall': lambda v: f'{v:.2f}',
            'calibration_threshold': lambda v: f'{v:.6f}',
            'calibration_fcr': pct,
            'future_recall': pct,
            'future_fcr': pct,
        },
    ),
    '',
    '## Walk-forward 요약',
    '',
    md_table(
        walk_summary_report,
        {
            'target_recall': lambda v: f'{v:.2f}',
            'mean_future_recall': pct,
            'min_future_recall': pct,
            'mean_future_fp': lambda v: f'{v:,.1f}',
            'mean_future_fcr': pct,
        },
    ),
    '',
    '## Final Retrospective Benchmark',
    '',
    '아래 Test는 이전 실험들과 같은 80~100% 구간이며, 이번 실험에서도 threshold 선택에는 사용하지 않았다.',
    '',
    md_table(
        final_report,
        {
            'target_recall': lambda v: f'{v:.2f}',
            'validation_threshold': lambda v: f'{v:.6f}',
            'validation_fcr': pct,
            'test_recall': pct,
            'test_fcr': pct,
        },
    ),
    '',
    f'## Prediction Disagreement / FN Overlap Diagnostic (target recall {DIAGNOSTIC_TARGET:.2f})',
    '',
    md_table(
        diagnostic_report,
        {
            'target_recall': lambda v: f'{v:.2f}',
            'disagreement_rate': pct,
            'probability_corr': lambda v: f'{v:.4f}',
        },
    ),
    '',
    '## 결론',
    '',
    *conclusion_lines,
    '',
    '## 실행 로그',
    '',
    f'`docs/peace/{LOG_PATH.name}`',
])
REPORT_PATH.write_text(report_text + '\n', encoding='utf-8')
display(Markdown(report_text[:4000]))
print(f'report saved to: {REPORT_PATH.relative_to(REPO_ROOT)}')
logger.info('report_saved=%s', REPORT_PATH.name)
logger.info('experiment_complete=%s', EXPERIMENT_ID)
for handler in logger.handlers:
    handler.flush()

2026-08-25 14:27:38,237 | INFO | experiment=0825_peace_012_recall_aligned_model_comparison

2026-08-25 14:27:38,237 | INFO | data_file=dataset.csv sha256=53e8568743216d556856ed69b388f6750fbfa0b8c59ad31f970515ac9eb10e62

2026-08-25 14:27:38,238 | INFO | mapping_file=mapping.json sha256=3b20f440b6d9ed0baefa662e1a6f03688befbe0f28341a3b54655d3058c6e486

2026-08-25 14:27:38,238 | INFO | versions python=3.12.7 pandas=2.2.2 sklearn=1.5.1 xgboost=3.4.1

2026-08-25 14:27:38,239 | INFO | target_recalls=[0.95, 0.97, 0.99] diagnostic_target=0.97

log saved to: docs/peace/0825_peace_012_recall_aligned_model_comparison.log

rows                                       440274
columns                                        78
false_call_0                               435652
real_defect_1                                4622
real_defect_rate_pct                     1.049801
inspection_types                                5
inspection_features                            70
mapped_feature_union                           65
timestamp_start         1970-06-23 03:58:55+00:00
timestamp_end           1970-11-02 14:21:28+00:00
Name: raw_data, dtype: object

                 meta_features  mapped_inspection_features  raw_features_used
inspection_type
0                            4                          44                 48
1                            4                          52                 56
2                            4                          65                 69
3                            4                          65                 69
4                            4                          21                 25

2026-08-25 14:27:42,847 | INFO | data_verified rows=440274 columns=78 class_0=435652 class_1=4622

              rows  positive_samples  positive_rate_pct  timestamp_groups                start_time                  end_time
split
train       308196              1940           0.629470             29249 1970-06-23 03:58:55+00:00 1970-10-05 00:29:59+00:00
validation   44026               357           0.810884              3400 1970-10-05 00:30:30+00:00 1970-10-13 16:54:14+00:00
test         88052              2325           2.640485              7093 1970-10-13 16:54:52+00:00 1970-11-02 14:21:28+00:00

2026-08-25 14:27:42,908 | INFO | split_summary=[{'split': 'train', 'rows': 308196, 'positive_samples': 1940, 'positive_rate_pct': 0.6294695583330089, 'timestamp_groups': 29249, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-10-05 00:29:59+0000', tz='UTC')}, {'split': 'validation', 'rows': 44026, 'positive_samples': 357, 'positive_rate_pct': 0.8108844773542907, 'timestamp_groups': 3400, 'start_time': Timestamp('1970-10-05 00:30:30+0000', tz='UTC'), 'end_time': Timestamp('1970-10-13 16:54:14+0000', tz='UTC')}, {'split': 'test', 'rows': 88052, 'positive_samples': 2325, 'positive_rate_pct': 2.640485167855358, 'timestamp_groups': 7093, 'start_time': Timestamp('1970-10-13 16:54:52+0000', tz='UTC'), 'end_time': Timestamp('1970-11-02 14:21:28+0000', tz='UTC')}]

                      rows  positive_samples  positive_rate_pct  timestamp_groups                start_time                  end_time
fold   segment
fold_1 train        132137              1223           0.925555             15230 1970-06-23 03:58:55+00:00 1970-08-18 06:51:10+00:00
       calibration   43979               200           0.454763              1251 1970-08-18 06:51:41+00:00 1970-08-21 23:32:59+00:00
       evaluation    44040               326           0.740236              5415 1970-08-21 23:33:55+00:00 1970-09-15 06:46:33+00:00
fold_2 train        176116              1423           0.807990             16481 1970-06-23 03:58:55+00:00 1970-08-21 23:32:59+00:00
       calibration   44040               326           0.740236              5415 1970-08-21 23:33:55+00:00 1970-09-15 06:46:33+00:00
       evaluation    44187               152           0.343993              4167 1970-09-15 06:47:13+00:00 1970-09-28 05:10:37+00:00
fold_3 train        220156              1749           0.794437             21896 1970-06-23 03:58:55+00:00 1970-09-15 06:46:33+00:00
       calibration   44187               152           0.343993              4167 1970-09-15 06:47:13+00:00 1970-09-28 05:10:37+00:00
       evaluation    43853                39           0.088933              3186 1970-09-28 05:11:13+00:00 1970-10-05 00:29:59+00:00

2026-08-25 14:27:43,044 | INFO | walk_forward_split_summary=[{'fold': 'fold_1', 'segment': 'train', 'rows': 132137, 'positive_samples': 1223, 'positive_rate_pct': 0.9255545380930399, 'timestamp_groups': 15230, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-08-18 06:51:10+0000', tz='UTC')}, {'fold': 'fold_1', 'segment': 'calibration', 'rows': 43979, 'positive_samples': 200, 'positive_rate_pct': 0.4547625002842266, 'timestamp_groups': 1251, 'start_time': Timestamp('1970-08-18 06:51:41+0000', tz='UTC'), 'end_time': Timestamp('1970-08-21 23:32:59+0000', tz='UTC')}, {'fold': 'fold_1', 'segment': 'evaluation', 'rows': 44040, 'positive_samples': 326, 'positive_rate_pct': 0.740236148955495, 'timestamp_groups': 5415, 'start_time': Timestamp('1970-08-21 23:33:55+0000', tz='UTC'), 'end_time': Timestamp('1970-09-15 06:46:33+0000', tz='UTC')}, {'fold': 'fold_2', 'segment': 'train', 'rows': 176116, 'positive_samples': 1423, 'positive_rate_pct': 0.8079901882849939, 'timestamp_groups': 16481, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-08-21 23:32:59+0000', tz='UTC')}, {'fold': 'fold_2', 'segment': 'calibration', 'rows': 44040, 'positive_samples': 326, 'positive_rate_pct': 0.740236148955495, 'timestamp_groups': 5415, 'start_time': Timestamp('1970-08-21 23:33:55+0000', tz='UTC'), 'end_time': Timestamp('1970-09-15 06:46:33+0000', tz='UTC')}, {'fold': 'fold_2', 'segment': 'evaluation', 'rows': 44187, 'positive_samples': 152, 'positive_rate_pct': 0.34399257700228575, 'timestamp_groups': 4167, 'start_time': Timestamp('1970-09-15 06:47:13+0000', tz='UTC'), 'end_time': Timestamp('1970-09-28 05:10:37+0000', tz='UTC')}, {'fold': 'fold_3', 'segment': 'train', 'rows': 220156, 'positive_samples': 1749, 'positive_rate_pct': 0.7944366721779101, 'timestamp_groups': 21896, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-09-15 06:46:33+0000', tz='UTC')}, {'fold': 'fold_3', 'segment': 'calibration', 'rows': 44187, 'positive_samples': 152, 'positive_rate_pct': 0.34399257700228575, 'timestamp_groups': 4167, 'start_time': Timestamp('1970-09-15 06:47:13+0000', tz='UTC'), 'end_time': Timestamp('1970-09-28 05:10:37+0000', tz='UTC')}, {'fold': 'fold_3', 'segment': 'evaluation', 'rows': 43853, 'positive_samples': 39, 'positive_rate_pct': 0.08893348231591909, 'timestamp_groups': 3186, 'start_time': Timestamp('1970-09-28 05:11:13+0000', tz='UTC'), 'end_time': Timestamp('1970-10-05 00:29:59+0000', tz='UTC')}]

2026-08-25 14:27:43,068 | INFO | threshold_selector_unit_test=PASS

2026-08-25 14:27:43,073 | INFO | fit_start model=003_004_single_unweighted stage=fold_1 type=0 train_rows=28277 train_positive=32 scale_pos_weight=1.000000

2026-08-25 14:27:43,397 | INFO | fit_done model=003_004_single_unweighted stage=fold_1 type=0

2026-08-25 14:27:43,436 | INFO | fit_start model=003_004_single_unweighted stage=fold_1 type=1 train_rows=22698 train_positive=269 scale_pos_weight=1.000000

2026-08-25 14:27:43,820 | INFO | fit_done model=003_004_single_unweighted stage=fold_1 type=1

2026-08-25 14:27:43,853 | INFO | fit_start model=003_004_single_unweighted stage=fold_1 type=2 train_rows=42288 train_positive=408 scale_pos_weight=1.000000

2026-08-25 14:27:44,566 | INFO | fit_done model=003_004_single_unweighted stage=fold_1 type=2

2026-08-25 14:27:44,596 | INFO | fit_start model=003_004_single_unweighted stage=fold_1 type=3 train_rows=37264 train_positive=510 scale_pos_weight=1.000000

2026-08-25 14:27:45,187 | INFO | fit_done model=003_004_single_unweighted stage=fold_1 type=3

2026-08-25 14:27:45,212 | INFO | fit_start model=003_004_single_unweighted stage=fold_1 type=4 train_rows=1610 train_positive=4 scale_pos_weight=1.000000

2026-08-25 14:27:45,267 | INFO | fit_done model=003_004_single_unweighted stage=fold_1 type=4

2026-08-25 14:27:45,317 | INFO | fit_start model=003_004_single_unweighted stage=fold_2 type=0 train_rows=36685 train_positive=43 scale_pos_weight=1.000000

2026-08-25 14:27:45,817 | INFO | fit_done model=003_004_single_unweighted stage=fold_2 type=0

2026-08-25 14:27:45,854 | INFO | fit_start model=003_004_single_unweighted stage=fold_2 type=1 train_rows=26566 train_positive=289 scale_pos_weight=1.000000

2026-08-25 14:27:46,538 | INFO | fit_done model=003_004_single_unweighted stage=fold_2 type=1

2026-08-25 14:27:46,574 | INFO | fit_start model=003_004_single_unweighted stage=fold_2 type=2 train_rows=58736 train_positive=500 scale_pos_weight=1.000000

2026-08-25 14:27:47,378 | INFO | fit_done model=003_004_single_unweighted stage=fold_2 type=2

2026-08-25 14:27:47,410 | INFO | fit_start model=003_004_single_unweighted stage=fold_2 type=3 train_rows=51683 train_positive=583 scale_pos_weight=1.000000

2026-08-25 14:27:48,196 | INFO | fit_done model=003_004_single_unweighted stage=fold_2 type=3

2026-08-25 14:27:48,223 | INFO | fit_start model=003_004_single_unweighted stage=fold_2 type=4 train_rows=2446 train_positive=8 scale_pos_weight=1.000000

2026-08-25 14:27:48,292 | INFO | fit_done model=003_004_single_unweighted stage=fold_2 type=4

2026-08-25 14:27:48,356 | INFO | fit_start model=003_004_single_unweighted stage=fold_3 type=0 train_rows=43181 train_positive=93 scale_pos_weight=1.000000

2026-08-25 14:27:48,843 | INFO | fit_done model=003_004_single_unweighted stage=fold_3 type=0

2026-08-25 14:27:48,872 | INFO | fit_start model=003_004_single_unweighted stage=fold_3 type=1 train_rows=29184 train_positive=475 scale_pos_weight=1.000000

2026-08-25 14:27:49,315 | INFO | fit_done model=003_004_single_unweighted stage=fold_3 type=1

2026-08-25 14:27:49,351 | INFO | fit_start model=003_004_single_unweighted stage=fold_3 type=2 train_rows=77700 train_positive=549 scale_pos_weight=1.000000

2026-08-25 14:27:50,254 | INFO | fit_done model=003_004_single_unweighted stage=fold_3 type=2

2026-08-25 14:27:50,286 | INFO | fit_start model=003_004_single_unweighted stage=fold_3 type=3 train_rows=67320 train_positive=622 scale_pos_weight=1.000000

2026-08-25 14:27:51,141 | INFO | fit_done model=003_004_single_unweighted stage=fold_3 type=3

2026-08-25 14:27:51,173 | INFO | fit_start model=003_004_single_unweighted stage=fold_3 type=4 train_rows=2771 train_positive=10 scale_pos_weight=1.000000

2026-08-25 14:27:51,364 | INFO | fit_done model=003_004_single_unweighted stage=fold_3 type=4

2026-08-25 14:27:51,436 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=0 train_rows=28277 train_positive=32 scale_pos_weight=1.000000

2026-08-25 14:27:51,776 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=0

2026-08-25 14:27:51,805 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=1 train_rows=22698 train_positive=269 scale_pos_weight=1.000000

2026-08-25 14:27:52,176 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=1

2026-08-25 14:27:52,204 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=2 train_rows=42288 train_positive=408 scale_pos_weight=1.000000

2026-08-25 14:27:52,873 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=2

2026-08-25 14:27:52,904 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=3 train_rows=37264 train_positive=510 scale_pos_weight=1.000000

2026-08-25 14:27:53,578 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=3

2026-08-25 14:27:53,602 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=4 train_rows=1610 train_positive=4 scale_pos_weight=1.000000

2026-08-25 14:27:53,659 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.30 type=4

2026-08-25 14:27:53,715 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=0 train_rows=36685 train_positive=43 scale_pos_weight=1.000000

2026-08-25 14:27:54,111 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=0

2026-08-25 14:27:54,141 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=1 train_rows=26566 train_positive=289 scale_pos_weight=1.000000

2026-08-25 14:27:54,588 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=1

2026-08-25 14:27:54,620 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=2 train_rows=58736 train_positive=500 scale_pos_weight=1.000000

2026-08-25 14:27:55,439 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=2

2026-08-25 14:27:55,472 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=3 train_rows=51683 train_positive=583 scale_pos_weight=1.000000

2026-08-25 14:27:56,205 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=3

2026-08-25 14:27:56,235 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=4 train_rows=2446 train_positive=8 scale_pos_weight=1.000000

2026-08-25 14:27:56,439 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.40 type=4

2026-08-25 14:27:56,508 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=0 train_rows=43181 train_positive=93 scale_pos_weight=1.000000

2026-08-25 14:27:57,015 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=0

2026-08-25 14:27:57,046 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=1 train_rows=29184 train_positive=475 scale_pos_weight=1.000000

2026-08-25 14:27:57,517 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=1

2026-08-25 14:27:57,556 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=2 train_rows=77700 train_positive=549 scale_pos_weight=1.000000

2026-08-25 14:27:58,410 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=2

2026-08-25 14:27:58,443 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=3 train_rows=67320 train_positive=622 scale_pos_weight=1.000000

2026-08-25 14:27:59,215 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=3

2026-08-25 14:27:59,245 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=4 train_rows=2771 train_positive=10 scale_pos_weight=1.000000

2026-08-25 14:27:59,297 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.50 type=4

2026-08-25 14:27:59,386 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=0 train_rows=64273 train_positive=111 scale_pos_weight=1.000000

2026-08-25 14:27:59,965 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=0

2026-08-25 14:27:59,996 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=1 train_rows=38900 train_positive=580 scale_pos_weight=1.000000

2026-08-25 14:28:00,447 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=1

2026-08-25 14:28:00,497 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=2 train_rows=100470 train_positive=588 scale_pos_weight=1.000000

2026-08-25 14:28:01,695 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=2

2026-08-25 14:28:01,734 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=3 train_rows=100740 train_positive=648 scale_pos_weight=1.000000

2026-08-25 14:28:02,636 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=3

2026-08-25 14:28:02,665 | INFO | fit_start model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=4 train_rows=3813 train_positive=13 scale_pos_weight=1.000000

2026-08-25 14:28:02,726 | INFO | fit_done model=005_expanding_fold_ensemble stage=checkpoint_0.70 type=4

2026-08-25 14:28:02,754 | INFO | fit_start model=007_single_class_weight stage=fold_1 type=0 train_rows=28277 train_positive=32 scale_pos_weight=882.656250

2026-08-25 14:28:03,252 | INFO | fit_done model=007_single_class_weight stage=fold_1 type=0

2026-08-25 14:28:03,279 | INFO | fit_start model=007_single_class_weight stage=fold_1 type=1 train_rows=22698 train_positive=269 scale_pos_weight=83.379182

2026-08-25 14:28:03,652 | INFO | fit_done model=007_single_class_weight stage=fold_1 type=1

2026-08-25 14:28:03,681 | INFO | fit_start model=007_single_class_weight stage=fold_1 type=2 train_rows=42288 train_positive=408 scale_pos_weight=102.647059

2026-08-25 14:28:04,290 | INFO | fit_done model=007_single_class_weight stage=fold_1 type=2

2026-08-25 14:28:04,318 | INFO | fit_start model=007_single_class_weight stage=fold_1 type=3 train_rows=37264 train_positive=510 scale_pos_weight=72.066667

2026-08-25 14:28:04,897 | INFO | fit_done model=007_single_class_weight stage=fold_1 type=3

2026-08-25 14:28:04,923 | INFO | fit_start model=007_single_class_weight stage=fold_1 type=4 train_rows=1610 train_positive=4 scale_pos_weight=401.500000

2026-08-25 14:28:04,990 | INFO | fit_done model=007_single_class_weight stage=fold_1 type=4

2026-08-25 14:28:05,020 | INFO | fit_start model=007_single_class_weight stage=fold_2 type=0 train_rows=36685 train_positive=43 scale_pos_weight=852.139535

2026-08-25 14:28:05,607 | INFO | fit_done model=007_single_class_weight stage=fold_2 type=0

2026-08-25 14:28:05,636 | INFO | fit_start model=007_single_class_weight stage=fold_2 type=1 train_rows=26566 train_positive=289 scale_pos_weight=90.923875

2026-08-25 14:28:06,033 | INFO | fit_done model=007_single_class_weight stage=fold_2 type=1

2026-08-25 14:28:06,064 | INFO | fit_start model=007_single_class_weight stage=fold_2 type=2 train_rows=58736 train_positive=500 scale_pos_weight=116.472000

2026-08-25 14:28:06,953 | INFO | fit_done model=007_single_class_weight stage=fold_2 type=2

2026-08-25 14:28:06,984 | INFO | fit_start model=007_single_class_weight stage=fold_2 type=3 train_rows=51683 train_positive=583 scale_pos_weight=87.650086

2026-08-25 14:28:07,664 | INFO | fit_done model=007_single_class_weight stage=fold_2 type=3

2026-08-25 14:28:07,689 | INFO | fit_start model=007_single_class_weight stage=fold_2 type=4 train_rows=2446 train_positive=8 scale_pos_weight=304.750000

2026-08-25 14:28:07,810 | INFO | fit_done model=007_single_class_weight stage=fold_2 type=4

2026-08-25 14:28:07,848 | INFO | fit_start model=007_single_class_weight stage=fold_3 type=0 train_rows=43181 train_positive=93 scale_pos_weight=463.311828

2026-08-25 14:28:08,500 | INFO | fit_done model=007_single_class_weight stage=fold_3 type=0

2026-08-25 14:28:08,530 | INFO | fit_start model=007_single_class_weight stage=fold_3 type=1 train_rows=29184 train_positive=475 scale_pos_weight=60.440000

2026-08-25 14:28:08,983 | INFO | fit_done model=007_single_class_weight stage=fold_3 type=1

2026-08-25 14:28:09,017 | INFO | fit_start model=007_single_class_weight stage=fold_3 type=2 train_rows=77700 train_positive=549 scale_pos_weight=140.530055

2026-08-25 14:28:09,924 | INFO | fit_done model=007_single_class_weight stage=fold_3 type=2

2026-08-25 14:28:09,958 | INFO | fit_start model=007_single_class_weight stage=fold_3 type=3 train_rows=67320 train_positive=622 scale_pos_weight=107.231511

2026-08-25 14:28:10,768 | INFO | fit_done model=007_single_class_weight stage=fold_3 type=3

2026-08-25 14:28:10,794 | INFO | fit_start model=007_single_class_weight stage=fold_3 type=4 train_rows=2771 train_positive=10 scale_pos_weight=276.100000

2026-08-25 14:28:10,917 | INFO | fit_done model=007_single_class_weight stage=fold_3 type=4

2026-08-25 14:28:11,188 | INFO | walk_evaluated model=003_004_single_unweighted fold=fold_1

2026-08-25 14:28:11,434 | INFO | walk_evaluated model=003_004_single_unweighted fold=fold_2

2026-08-25 14:28:11,682 | INFO | walk_evaluated model=003_004_single_unweighted fold=fold_3

2026-08-25 14:28:11,918 | INFO | walk_evaluated model=005_expanding_fold_ensemble fold=fold_1

2026-08-25 14:28:12,160 | INFO | walk_evaluated model=005_expanding_fold_ensemble fold=fold_2

2026-08-25 14:28:12,399 | INFO | walk_evaluated model=005_expanding_fold_ensemble fold=fold_3

2026-08-25 14:28:12,644 | INFO | walk_evaluated model=007_single_class_weight fold=fold_1

2026-08-25 14:28:12,889 | INFO | walk_evaluated model=007_single_class_weight fold=fold_2

2026-08-25 14:28:13,129 | INFO | walk_evaluated model=007_single_class_weight fold=fold_3

/var/folders/hr/d68j34t15ml26bj24ghrh8cc0000gn/T/ipykernel_30091/2426572052.py:649: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  walk_summary = walk_results.groupby(['target_recall', 'model_id', 'model_label'], sort=True).apply(summarize_walk).reset_index()

,model_id,model_label,fold,target_recall,calibration_rows,calibration_positive_samples,calibration_threshold,calibration_recall,calibration_fp,calibration_fn,calibration_fcr,future_rows,future_positive_samples,future_recall,future_fp,future_fn,future_fcr,future_precision,future_pr_auc,future_tp,future_tn
0,003_004_single_unweighted,003/004 single type-expert,fold_1,0.95,43979,200,0.000415,0.950000,31728,10,0.275269,44040,326,0.987730,34809,4,0.203710,0.009166,0.134269,322,8905
1,003_004_single_unweighted,003/004 single type-expert,fold_2,0.95,44040,326,0.001509,0.957055,21761,14,0.502196,44187,152,0.848684,19172,23,0.564619,0.006684,0.024969,129,24863
2,003_004_single_unweighted,003/004 single type-expert,fold_3,0.95,44187,152,0.000240,0.953947,26207,7,0.404860,43853,39,0.974359,32539,1,0.257338,0.001166,0.034459,38,11275
3,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_1,0.95,43979,200,0.000415,0.950000,31728,10,0.275269,44040,326,0.987730,34809,4,0.203710,0.009166,0.134269,322,8905
4,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_2,0.95,44040,326,0.001926,0.963190,20834,12,0.523402,44187,152,0.842105,17960,24,0.592143,0.007077,0.028310,128,26075
5,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_3,0.95,44187,152,0.000436,0.953947,30228,7,0.313546,43853,39,0.974359,30580,1,0.302050,0.001241,0.037427,38,13234
6,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_1,0.95,43979,200,0.000449,0.950000,32042,10,0.268097,44040,326,0.990798,36875,3,0.156449,0.008683,0.245426,323,6839
7,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_2,0.95,44040,326,0.009488,0.950920,18663,16,0.573066,44187,152,0.782895,14692,33,0.666356,0.008035,0.042780,119,29343
8,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_3,0.95,44187,152,0.000876,0.953947,24136,7,0.451891,43853,39,0.974359,29119,1,0.335395,0.001303,0.010187,38,14695
9,003_004_single_unweighted,003/004 single type-expert,fold_1,0.97,43979,200,0.000277,0.970000,35132,6,0.197515,44040,326,0.993865,37504,2,0.142060,0.008565,0.134269,324,6210
10,003_004_single_unweighted,003/004 single type-expert,fold_2,0.97,44040,326,0.000886,0.975460,26482,8,0.394199,44187,152,0.894737,23231,16,0.472442,0.005820,0.024969,136,20804
11,003_004_single_unweighted,003/004 single type-expert,fold_3,0.97,44187,152,0.000134,0.973684,34303,4,0.221006,43853,39,1.000000,36598,0,0.164696,0.001064,0.034459,39,7216
12,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_1,0.97,43979,200,0.000277,0.970000,35132,6,0.197515,44040,326,0.993865,37504,2,0.142060,0.008565,0.134269,324,6210
13,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_2,0.97,44040,326,0.001614,0.972393,23028,9,0.473212,44187,152,0.842105,19297,24,0.561780,0.006589,0.028310,128,24738
14,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_3,0.97,44187,152,0.000351,0.973684,31612,4,0.282116,43853,39,0.974359,32013,1,0.269343,0.001186,0.037427,38,11801
15,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_1,0.97,43979,200,0.000405,0.970000,33292,6,0.239544,44040,326,0.990798,37968,3,0.131445,0.008435,0.245426,323,5746
16,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_2,0.97,44040,326,0.004600,0.972393,24769,9,0.433385,44187,152,0.861842,19541,21,0.556239,0.006659,0.042780,131,24494
17,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_3,0.97,44187,152,0.000520,0.973684,29640,4,0.326899,43853,39,0.974359,33363,1,0.238531,0.001138,0.010187,38,10451
18,003_004_single_unweighted,003/004 single type-expert,fold_1,0.99,43979,200,0.000027,0.990000,43234,2,0.012449,44040,326,1.000000,43327,0,0.008853,0.007468,0.134269,326,387
19,003_004_single_unweighted,003/004 single type-expert,fold_2,0.99,44040,326,0.000680,0.990798,28059,3,0.358123,44187,152,0.907895,25068,14,0.430726,0.005475,0.024969,138,18967
20,003_004_single_unweighted,003/004 single type-expert,fold_3,0.99,44187,152,0.000065,0.993421,40450,1,0.081413,43853,39,1.000000,40801,0,0.068768,0.000955,0.034459,39,3013
21,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_1,0.99,43979,200,0.000027,0.990000,43234,2,0.012449,44040,326,1.000000,43327,0,0.008853,0.007468,0.134269,326,387
22,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_2,0.99,44040,326,0.000488,0.990798,33668,3,0.229812,44187,152,0.960526,29122,6,0.338662,0.004988,0.028310,146,14913
23,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,fold_3,0.99,44187,152,0.000204,0.993421,35026,1,0.204587,43853,39,1.000000,35859,0,0.181563,0.001086,0.037427,39,7955
24,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_1,0.99,43979,200,0.000194,0.990000,38172,2,0.128075,44040,326,0.996933,40707,1,0.068788,0.007921,0.245426,325,3007
25,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_2,0.99,44040,326,0.001389,0.990798,31664,3,0.275655,44187,152,0.953947,26479,7,0.398683,0.005446,0.042780,145,17556
26,007_single_class_weight,007 single type-expert + scale_pos_weight,fold_3,0.99,44187,152,0.000135,0.993421,39796,1,0.096264,43853,39,1.000000,42125,0,0.038549,0.000925,0.010187,39,1689

,target_recall,model_id,model_label,folds,mean_calibration_threshold,mean_future_recall,min_future_recall,recall_target_hit_folds,mean_future_fp,total_future_fp,mean_future_fn,mean_future_fcr
0,0.95,007_single_class_weight,007 single type-expert + scale_pos_weight,3.0,0.003604,0.916017,0.782895,2.0,26895.333333,80686.0,12.333333,0.386067
1,0.95,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,3.0,0.000925,0.934731,0.842105,2.0,27783.000000,83349.0,9.666667,0.365968
2,0.95,003_004_single_unweighted,003/004 single type-expert,3.0,0.000721,0.936924,0.848684,2.0,28840.000000,86520.0,9.333333,0.341889
3,0.97,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,3.0,0.000747,0.936776,0.842105,2.0,29604.666667,88814.0,9.000000,0.324394
4,0.97,007_single_class_weight,007 single type-expert + scale_pos_weight,3.0,0.001842,0.942333,0.861842,2.0,30290.666667,90872.0,8.333333,0.308739
5,0.97,003_004_single_unweighted,003/004 single type-expert,3.0,0.000432,0.962867,0.894737,2.0,32444.333333,97333.0,6.000000,0.259733
6,0.99,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,3.0,0.000240,0.986842,0.960526,2.0,36102.666667,108308.0,2.000000,0.176359
7,0.99,003_004_single_unweighted,003/004 single type-expert,3.0,0.000258,0.969298,0.907895,2.0,36398.666667,109196.0,4.666667,0.169449
8,0.99,007_single_class_weight,007 single type-expert + scale_pos_weight,3.0,0.000573,0.983627,0.953947,2.0,36437.000000,109311.0,2.666667,0.168673

2026-08-25 14:28:13,147 | INFO | walk_summary=[{'target_recall': 0.95, 'model_id': '007_single_class_weight', 'model_label': '007 single type-expert + scale_pos_weight', 'folds': 3.0, 'mean_calibration_threshold': 0.00360436057477879, 'mean_future_recall': 0.9160170857377832, 'min_future_recall': 0.7828947368421053, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 26895.333333333332, 'total_future_fp': 80686.0, 'mean_future_fn': 12.333333333333334, 'mean_future_fcr': 0.3860667072133886}, {'target_recall': 0.95, 'model_id': '005_expanding_fold_ensemble', 'model_label': '005 expanding checkpoint ensemble', 'folds': 3.0, 'mean_calibration_threshold': 0.0009254446777049452, 'mean_future_recall': 0.9347314329555209, 'min_future_recall': 0.8421052631578947, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 27783.0, 'total_future_fp': 83349.0, 'mean_future_fn': 9.666666666666666, 'mean_future_fcr': 0.365967556264515}, {'target_recall': 0.95, 'model_id': '003_004_single_unweighted', 'model_label': '003/004 single type-expert', 'folds': 3.0, 'mean_calibration_threshold': 0.0007212491473183036, 'mean_future_recall': 0.936924415411661, 'min_future_recall': 0.8486842105263158, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 28840.0, 'total_future_fp': 86520.0, 'mean_future_fn': 9.333333333333334, 'mean_future_fcr': 0.34188912400494537}, {'target_recall': 0.97, 'model_id': '005_expanding_fold_ensemble', 'model_label': '005 expanding checkpoint ensemble', 'folds': 3.0, 'mean_calibration_threshold': 0.0007471374523851814, 'mean_future_recall': 0.9367764227305719, 'min_future_recall': 0.8421052631578947, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 29604.666666666668, 'total_future_fp': 88814.0, 'mean_future_fn': 9.0, 'mean_future_fcr': 0.3243944287698821}, {'target_recall': 0.97, 'model_id': '007_single_class_weight', 'model_label': '007 single type-expert + scale_pos_weight', 'folds': 3.0, 'mean_calibration_threshold': 0.001841693922566871, 'mean_future_recall': 0.9423328752114674, 'min_future_recall': 0.8618421052631579, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 30290.666666666668, 'total_future_fp': 90872.0, 'mean_future_fn': 8.333333333333334, 'mean_future_fcr': 0.308738573917686}, {'target_recall': 0.97, 'model_id': '003_004_single_unweighted', 'model_label': '003/004 single type-expert', 'folds': 3.0, 'mean_calibration_threshold': 0.00043211942344593507, 'mean_future_recall': 0.9628672909267033, 'min_future_recall': 0.8947368421052632, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 32444.333333333332, 'total_future_fp': 97333.0, 'mean_future_fn': 6.0, 'mean_future_fcr': 0.25973278107638925}, {'target_recall': 0.99, 'model_id': '005_expanding_fold_ensemble', 'model_label': '005 expanding checkpoint ensemble', 'folds': 3.0, 'mean_calibration_threshold': 0.00023991252197043246, 'mean_future_recall': 0.9868421052631579, 'min_future_recall': 0.9605263157894737, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 36102.666666666664, 'total_future_fp': 108308.0, 'mean_future_fn': 2.0, 'mean_future_fcr': 0.17635946579785103}, {'target_recall': 0.99, 'model_id': '003_004_single_unweighted', 'model_label': '003/004 single type-expert', 'folds': 3.0, 'mean_calibration_threshold': 0.00025751433592328493, 'mean_future_recall': 0.9692982456140351, 'min_future_recall': 0.9078947368421053, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 36398.666666666664, 'total_future_fp': 109196.0, 'mean_future_fn': 4.666666666666667, 'mean_future_fcr': 0.16944884398683502}, {'target_recall': 0.99, 'model_id': '007_single_class_weight', 'model_label': '007 single type-expert + scale_pos_weight', 'folds': 3.0, 'mean_calibration_threshold': 0.0005729094070071975, 'mean_future_recall': 0.983626627919492, 'min_future_recall': 0.9539473684210527, 'recall_target_hit_folds': 2.0, 'mean_future_fp': 36437.0, 'total_future_fp': 109311.0, 'mean_future_fn': 2.6666666666666665, 'mean_future_fcr': 0.16867340644364104}]

2026-08-25 14:28:13,216 | INFO | fit_start model=003_004_single_unweighted stage=final_train70 type=0 train_rows=64273 train_positive=111 scale_pos_weight=1.000000

2026-08-25 14:28:13,902 | INFO | fit_done model=003_004_single_unweighted stage=final_train70 type=0

2026-08-25 14:28:13,937 | INFO | fit_start model=003_004_single_unweighted stage=final_train70 type=1 train_rows=38900 train_positive=580 scale_pos_weight=1.000000

2026-08-25 14:28:14,524 | INFO | fit_done model=003_004_single_unweighted stage=final_train70 type=1

2026-08-25 14:28:14,563 | INFO | fit_start model=003_004_single_unweighted stage=final_train70 type=2 train_rows=100470 train_positive=588 scale_pos_weight=1.000000

2026-08-25 14:28:15,649 | INFO | fit_done model=003_004_single_unweighted stage=final_train70 type=2

2026-08-25 14:28:15,689 | INFO | fit_start model=003_004_single_unweighted stage=final_train70 type=3 train_rows=100740 train_positive=648 scale_pos_weight=1.000000

2026-08-25 14:28:16,911 | INFO | fit_done model=003_004_single_unweighted stage=final_train70 type=3

2026-08-25 14:28:16,937 | INFO | fit_start model=003_004_single_unweighted stage=final_train70 type=4 train_rows=3813 train_positive=13 scale_pos_weight=1.000000

2026-08-25 14:28:16,995 | INFO | fit_done model=003_004_single_unweighted stage=final_train70 type=4

2026-08-25 14:28:17,053 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=0 train_rows=28277 train_positive=32 scale_pos_weight=1.000000

2026-08-25 14:28:17,335 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=0

2026-08-25 14:28:17,362 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=1 train_rows=22698 train_positive=269 scale_pos_weight=1.000000

2026-08-25 14:28:17,748 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=1

2026-08-25 14:28:17,777 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=2 train_rows=42288 train_positive=408 scale_pos_weight=1.000000

2026-08-25 14:28:18,363 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=2

2026-08-25 14:28:18,391 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=3 train_rows=37264 train_positive=510 scale_pos_weight=1.000000

2026-08-25 14:28:18,961 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=3

2026-08-25 14:28:18,990 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=4 train_rows=1610 train_positive=4 scale_pos_weight=1.000000

2026-08-25 14:28:19,071 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.30 type=4

2026-08-25 14:28:19,142 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=0 train_rows=36685 train_positive=43 scale_pos_weight=1.000000

2026-08-25 14:28:19,501 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=0

2026-08-25 14:28:19,531 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=1 train_rows=26566 train_positive=289 scale_pos_weight=1.000000

2026-08-25 14:28:19,956 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=1

2026-08-25 14:28:19,987 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=2 train_rows=58736 train_positive=500 scale_pos_weight=1.000000

2026-08-25 14:28:20,808 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=2

2026-08-25 14:28:20,875 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=3 train_rows=51683 train_positive=583 scale_pos_weight=1.000000

2026-08-25 14:28:21,757 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=3

2026-08-25 14:28:21,785 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=4 train_rows=2446 train_positive=8 scale_pos_weight=1.000000

2026-08-25 14:28:21,895 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.40 type=4

2026-08-25 14:28:21,970 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=0 train_rows=43181 train_positive=93 scale_pos_weight=1.000000

2026-08-25 14:28:22,478 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=0

2026-08-25 14:28:22,507 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=1 train_rows=29184 train_positive=475 scale_pos_weight=1.000000

2026-08-25 14:28:22,994 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=1

2026-08-25 14:28:23,030 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=2 train_rows=77700 train_positive=549 scale_pos_weight=1.000000

2026-08-25 14:28:23,939 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=2

2026-08-25 14:28:23,973 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=3 train_rows=67320 train_positive=622 scale_pos_weight=1.000000

2026-08-25 14:28:24,879 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=3

2026-08-25 14:28:24,912 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=4 train_rows=2771 train_positive=10 scale_pos_weight=1.000000

2026-08-25 14:28:24,980 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.50 type=4

2026-08-25 14:28:25,086 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=0 train_rows=64273 train_positive=111 scale_pos_weight=1.000000

2026-08-25 14:28:25,818 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=0

2026-08-25 14:28:25,850 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=1 train_rows=38900 train_positive=580 scale_pos_weight=1.000000

2026-08-25 14:28:26,697 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=1

2026-08-25 14:28:26,744 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=2 train_rows=100470 train_positive=588 scale_pos_weight=1.000000

2026-08-25 14:28:27,912 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=2

2026-08-25 14:28:27,951 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=3 train_rows=100740 train_positive=648 scale_pos_weight=1.000000

2026-08-25 14:28:29,022 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=3

2026-08-25 14:28:29,049 | INFO | fit_start model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=4 train_rows=3813 train_positive=13 scale_pos_weight=1.000000

2026-08-25 14:28:29,105 | INFO | fit_done model=005_expanding_fold_ensemble stage=final_checkpoint_0.70 type=4

2026-08-25 14:28:29,155 | INFO | fit_start model=007_single_class_weight stage=final_train70 type=0 train_rows=64273 train_positive=111 scale_pos_weight=578.036036

2026-08-25 14:28:30,013 | INFO | fit_done model=007_single_class_weight stage=final_train70 type=0

2026-08-25 14:28:30,045 | INFO | fit_start model=007_single_class_weight stage=final_train70 type=1 train_rows=38900 train_positive=580 scale_pos_weight=66.068966

2026-08-25 14:28:30,709 | INFO | fit_done model=007_single_class_weight stage=final_train70 type=1

2026-08-25 14:28:30,755 | INFO | fit_start model=007_single_class_weight stage=final_train70 type=2 train_rows=100470 train_positive=588 scale_pos_weight=169.867347

2026-08-25 14:28:31,983 | INFO | fit_done model=007_single_class_weight stage=final_train70 type=2

2026-08-25 14:28:32,022 | INFO | fit_start model=007_single_class_weight stage=final_train70 type=3 train_rows=100740 train_positive=648 scale_pos_weight=154.462963

2026-08-25 14:28:33,198 | INFO | fit_done model=007_single_class_weight stage=final_train70 type=3

2026-08-25 14:28:33,227 | INFO | fit_start model=007_single_class_weight stage=final_train70 type=4 train_rows=3813 train_positive=13 scale_pos_weight=292.307692

2026-08-25 14:28:33,416 | INFO | fit_done model=007_single_class_weight stage=final_train70 type=4

,model_id,model_label,target_recall,validation_threshold,validation_recall,validation_fp,validation_fcr,test_recall,test_fp,test_fn,test_fcr,test_precision,test_pr_auc,test_tp,test_tn,selection_note
0,003_004_single_unweighted,003/004 single type-expert,0.95,0.001947,0.952381,7995,0.816918,0.849892,21253,349,0.752085,0.085066,0.318360,1976,64474,Test reused from prior experiments; threshold ...
1,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,0.95,0.002278,0.952381,9306,0.786897,0.873118,25267,295,0.705262,0.074367,0.382545,2030,60460,Test reused from prior experiments; threshold ...
2,007_single_class_weight,007 single type-expert + scale_pos_weight,0.95,0.000480,0.952381,29246,0.330280,0.957849,66803,98,0.220747,0.032261,0.318605,2227,18924,Test reused from prior experiments; threshold ...
3,003_004_single_unweighted,003/004 single type-expert,0.97,0.001480,0.971989,8932,0.795461,0.864946,23338,314,0.727764,0.079333,0.318360,2011,62389,Test reused from prior experiments; threshold ...
4,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,0.97,0.001453,0.971989,11510,0.736426,0.904516,29572,222,0.655045,0.066393,0.382545,2103,56155,Test reused from prior experiments; threshold ...
5,007_single_class_weight,007 single type-expert + scale_pos_weight,0.97,0.000376,0.971989,31388,0.281229,0.964731,69875,82,0.184913,0.031102,0.318605,2243,15852,Test reused from prior experiments; threshold ...
6,003_004_single_unweighted,003/004 single type-expert,0.99,0.000770,0.991597,13127,0.699398,0.898065,33486,237,0.609388,0.058695,0.318360,2088,52241,Test reused from prior experiments; threshold ...
7,005_expanding_fold_ensemble,005 expanding checkpoint ensemble,0.99,0.000710,0.991597,16984,0.611074,0.939355,41118,141,0.520361,0.050436,0.382545,2184,44609,Test reused from prior experiments; threshold ...
8,007_single_class_weight,007 single type-expert + scale_pos_weight,0.99,0.000189,0.991597,36700,0.159587,0.984946,77110,35,0.100517,0.028841,0.318605,2290,8617,Test reused from prior experiments; threshold ...

2026-08-25 14:28:34,654 | INFO | final_results=[{'model_id': '003_004_single_unweighted', 'model_label': '003/004 single type-expert', 'target_recall': 0.95, 'validation_threshold': 0.0019472370622679591, 'validation_recall': 0.9523809523809523, 'validation_fp': 7995, 'validation_fcr': 0.8169181799445832, 'test_recall': 0.8498924731182795, 'test_fp': 21253, 'test_fn': 349, 'test_fcr': 0.7520851073757393, 'test_precision': 0.08506608119161393, 'test_pr_auc': 0.31836015100786796, 'test_tp': 1976, 'test_tn': 64474, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '005_expanding_fold_ensemble', 'model_label': '005 expanding checkpoint ensemble', 'target_recall': 0.95, 'validation_threshold': 0.0022782720188843086, 'validation_recall': 0.9523809523809523, 'validation_fp': 9306, 'validation_fcr': 0.7868968833726442, 'test_recall': 0.8731182795698925, 'test_fp': 25267, 'test_fn': 295, 'test_fcr': 0.705262052795502, 'test_precision': 0.07436714657288347, 'test_pr_auc': 0.38254500187536195, 'test_tp': 2030, 'test_tn': 60460, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '007_single_class_weight', 'model_label': '007 single type-expert + scale_pos_weight', 'target_recall': 0.95, 'validation_threshold': 0.00048028555465862155, 'validation_recall': 0.9523809523809523, 'validation_fp': 29246, 'validation_fcr': 0.33028006137076643, 'test_recall': 0.9578494623655914, 'test_fp': 66803, 'test_fn': 98, 'test_fcr': 0.22074725582371948, 'test_precision': 0.03226133565116616, 'test_pr_auc': 0.31860498449750563, 'test_tp': 2227, 'test_tn': 18924, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '003_004_single_unweighted', 'model_label': '003/004 single type-expert', 'target_recall': 0.97, 'validation_threshold': 0.0014802084770053625, 'validation_recall': 0.9719887955182073, 'validation_fp': 8932, 'validation_fcr': 0.7954613112276443, 'test_recall': 0.8649462365591398, 'test_fp': 23338, 'test_fn': 314, 'test_fcr': 0.7277637150489344, 'test_precision': 0.07933251804804924, 'test_pr_auc': 0.31836015100786796, 'test_tp': 2011, 'test_tn': 62389, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '005_expanding_fold_ensemble', 'model_label': '005 expanding checkpoint ensemble', 'target_recall': 0.97, 'validation_threshold': 0.001452848722692579, 'validation_recall': 0.9719887955182073, 'validation_fp': 11510, 'validation_fcr': 0.7364262978314136, 'test_recall': 0.9045161290322581, 'test_fp': 29572, 'test_fn': 222, 'test_fcr': 0.655044501732243, 'test_precision': 0.0663930544593528, 'test_pr_auc': 0.38254500187536195, 'test_tp': 2103, 'test_tn': 56155, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '007_single_class_weight', 'model_label': '007 single type-expert + scale_pos_weight', 'target_recall': 0.97, 'validation_threshold': 0.0003762348787859082, 'validation_recall': 0.9719887955182073, 'validation_fp': 31388, 'validation_fcr': 0.28122924729212945, 'test_recall': 0.9647311827956989, 'test_fp': 69875, 'test_fn': 82, 'test_fcr': 0.18491257130192354, 'test_precision': 0.031101805374525084, 'test_pr_auc': 0.31860498449750563, 'test_tp': 2243, 'test_tn': 15852, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '003_004_single_unweighted', 'model_label': '003/004 single type-expert', 'target_recall': 0.99, 'validation_threshold': 0.0007697296096011996, 'validation_recall': 0.9915966386554622, 'validation_fp': 13127, 'validation_fcr': 0.6993977421053836, 'test_recall': 0.8980645161290323, 'test_fp': 33486, 'test_fn': 237, 'test_fcr': 0.609387940788783, 'test_precision': 0.058694552201045705, 'test_pr_auc': 0.31836015100786796, 'test_tp': 2088, 'test_tn': 52241, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '005_expanding_fold_ensemble', 'model_label': '005 expanding checkpoint ensemble', 'target_recall': 0.99, 'validation_threshold': 0.0007097448979038745, 'validation_recall': 0.9915966386554622, 'validation_fp': 16984, 'validation_fcr': 0.6110742174082301, 'test_recall': 0.9393548387096774, 'test_fp': 41118, 'test_fn': 141, 'test_fcr': 0.5203611464299462, 'test_precision': 0.0504364694471387, 'test_pr_auc': 0.38254500187536195, 'test_tp': 2184, 'test_tn': 44609, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}, {'model_id': '007_single_class_weight', 'model_label': '007 single type-expert + scale_pos_weight', 'target_recall': 0.99, 'validation_threshold': 0.00018872492364607751, 'validation_recall': 0.9915966386554622, 'validation_fp': 36700, 'validation_fcr': 0.1595868923034647, 'test_recall': 0.9849462365591398, 'test_fp': 77110, 'test_fn': 35, 'test_fcr': 0.1005167566810923, 'test_precision': 0.028841309823677583, 'test_pr_auc': 0.31860498449750563, 'test_tp': 2290, 'test_tn': 8617, 'selection_note': 'Test reused from prior experiments; threshold selected on validation only.'}]

,target_recall,model_a,model_b,disagreement_rate,probability_corr,fn_a,fn_b,shared_fn,fn_only_a,fn_only_b,fp_a,fp_b,shared_fp,fp_only_a,fp_only_b
0,0.97,003_004_single_unweighted,005_expanding_fold_ensemble,0.079149,0.964839,18,27,18,0,9,97333,88814,87851,9482,963
1,0.97,003_004_single_unweighted,007_single_class_weight,0.144140,0.596982,18,25,8,10,17,97333,90872,84597,12736,6275
2,0.97,005_expanding_fold_ensemble,007_single_class_weight,0.153816,0.600241,27,25,13,14,12,88814,90872,79698,9116,11174

2026-08-25 14:28:35,027 | INFO | diagnostic_summary=[{'target_recall': 0.97, 'model_a': '003_004_single_unweighted', 'model_b': '005_expanding_fold_ensemble', 'disagreement_rate': 0.07914900060569352, 'probability_corr': 0.9648394493763093, 'fn_a': 18, 'fn_b': 27, 'shared_fn': 18, 'fn_only_a': 0, 'fn_only_b': 9, 'fp_a': 97333, 'fp_b': 88814, 'shared_fp': 87851, 'fp_only_a': 9482, 'fp_only_b': 963}, {'target_recall': 0.97, 'model_a': '003_004_single_unweighted', 'model_b': '007_single_class_weight', 'disagreement_rate': 0.14413991520290734, 'probability_corr': 0.5969821396799687, 'fn_a': 18, 'fn_b': 25, 'shared_fn': 8, 'fn_only_a': 10, 'fn_only_b': 17, 'fp_a': 97333, 'fp_b': 90872, 'shared_fp': 84597, 'fp_only_a': 12736, 'fp_only_b': 6275}, {'target_recall': 0.97, 'model_a': '005_expanding_fold_ensemble', 'model_b': '007_single_class_weight', 'disagreement_rate': 0.15381586917019988, 'probability_corr': 0.6002406231334938, 'fn_a': 27, 'fn_b': 25, 'shared_fn': 13, 'fn_only_a': 14, 'fn_only_b': 12, 'fp_a': 88814, 'fp_b': 90872, 'shared_fp': 79698, 'fp_only_a': 9116, 'fp_only_b': 11174}]

dataset_sha256_unchanged                                                 True
mapping_sha256_unchanged                                                 True
dataset_sha256              53e8568743216d556856ed69b388f6750fbfa0b8c59ad3...
mapping_sha256              3b20f440b6d9ed0baefa662e1a6f03688befbe0f28341a...
walk_rows                                                                  27
final_rows                                                                  9
diagnostic_pairs                                                            3
log_file                    docs/peace/0825_peace_012_recall_aligned_model...
report_file                 docs/experiments/0825_peace_012_recall_aligned...
Name: verification, dtype: object

2026-08-25 14:28:35,215 | INFO | source_integrity=PASS

# 0825_peace_012_recall_aligned_model_comparison

## 연결된 노트북

`notebooks/0825_peace_012_recall_aligned_model_comparison.ipynb`

## 상태

완료

## 목적

003/004 단일 type-expert, 005 expanding checkpoint ensemble, 007 type별 `scale_pos_weight` 모델을 동일한 분할·피처·XGBoost 파라미터에서 비교하고, 동일 Recall 목표에서 미래 Fold와 최종 Test의 FP/FCR 차이를 정리한다.

## 설정

- Target recall: [0.95, 0.97, 0.99]
- Walk-forward fold: 004/005와 동일한 expanding 3-fold
- Final benchmark: 0~70% Train / 70~80% Validation / 80~100% Test
- Threshold rule: 기존 `select_threshold` 로직 그대로 사용, calibration/validation에서 recall 제약을 만족하는 threshold 중 FCR 최대 선택
- Source integrity: dataset sha256 `53e8568743216d556856ed69b388f6750fbfa0b8c59ad31f970515ac9eb10e62`, mapping sha256 `3b20f440b6d9ed0baefa662e1a6f03688befbe0f28341a3b54655d3058c6e486`
- Log: `docs/peace/0825_peace_012_recall_aligned_model_comparison.log`

## 데이터 분할

| split      |   rows |   positive_samples |   positive_rate_pct |   timestamp_groups | start_time                | end_time                  |
|:-----------|-------:|-------------------:|--------------------:|-------------------:|:--------------------------|:--------------------------|
| train      | 308196 |               1940 |            0.62947  |              29249 | 1970-06-23 03:58:55+00:00 | 1970-10-05 00:29:59+00:00 |
| validation |  44026 |                357 |            0.810884 |               3400 | 1970-10-05 00:30:30+00:00 | 1970-10-13 16:54:14+00:00 |
| test       |  88052 |               2325 |            2.64049  |               7093 | 1970-10-13 16:54:52+00:00 | 1970-11-02 14:21:28+00:00 |

## Walk-forward 구성

| fold   | segment     |   rows |   positive_samples |   positive_rate_pct |   timestamp_groups | start_time                | end_time                  |
|:-------|:------------|-------:|-------------------:|--------------------:|-------------------:|:--------------------------|:--------------------------|
| fold_1 | train       | 132137 |               1223 |           0.925555  |              15230 | 1970-06-23 03:58:55+00:00 | 1970-08-18 06:51:10+00:00 |
| fold_1 | calibration |  43979 |                200 |           0.454763  |               1251 | 1970-08-18 06:51:41+00:00 | 1970-08-21 23:32:59+00:00 |
| fold_1 | evaluation  |  44040 |                326 |           0.740236  |               5415 | 1970-08-21 23:33:55+00:00 | 1970-09-15 06:46:33+00:00 |
| fold_2 | train       | 176116 |               1423 |           0.80799   |              16481 | 1970-06-23 03:58:55+00:00 | 1970-08-21 23:32:59+00:00 |
| fold_2 | calibration |  44040 |                326 |           0.740236  |               5415 | 1970-08-21 23:33:55+00:00 | 1970-09-15 06:46:33+00:00 |
| fold_2 | evaluation  |  44187 |                152 |           0.343993  |               4167 | 1970-09-15 06:47:13+00:00 | 1970-09-28 05:10:37+00:00 |
| fold_3 | train       | 220156 |               1749 |           0.794437  |              21896 | 1970-06-23 03:58:55+00:00 | 1970-09-15 06:46:33+00:00 |
| fold_3 | calibration |  44187 |                152 |           0.343993  |               4167 | 1970-09-15 06:47:13+00:00 | 1970-09-28 05:10:37+00:00 |
| fold_3 | evaluation  |  43853 |                 39 |           0.0889335 |               3186 | 1970-09-28 05:11:13+00:00 | 1970-10-05 00:29:59+00:00 |

## Fold별 Recall-aligned 결과

|   target_recall | model                                     | fold   |   calibration_threshold |   calibration_fp | calibration_fcr   | future_recall   |   future_fp | future_fcr   |   future_fn |
|----------------:|:------------------------------------------|:-------|------------------------:|-----------------:|:------------------|:----------------|------------:|:-------------|------------:|
|            0.95 | 003/004 single type-expert                | fold_1 |                0.000415 |            31728 | 27.53%            | 98.77%          |       34809 | 20.37%       |           4 |
|            0.95 | 003/004 single type-expert                | fold_2 |

report saved to: docs/experiments/0825_peace_012_recall_aligned_model_comparison.md
2026-08-25 14:28:35,229 | INFO | report_saved=0825_peace_012_recall_aligned_model_comparison.md

2026-08-25 14:28:35,229 | INFO | experiment_complete=0825_peace_012_recall_aligned_model_comparison