# 0825_peace_017_type_expert_typewise_meta_removal

타입마다 `meta_feat1~4`가 실제 도움이 되는지 다를 수 있다는 가정으로, `0825_peace_004_type_expert_walk_forward`를 기준으로 타입별 `with_meta` / `without_meta`를 Walk-forward에서 비교하고 Validation까지 재검증합니다.

- 기준 실험은 `0825_peace_004_type_expert_walk_forward`입니다.
- 데이터 분할, XGBoost 파라미터, 임계값 선택 규칙은 004와 동일합니다.
- 차이는 이 노트북의 피처 처리만입니다.
- 실행 로그는 `docs/peace/0825_peace_017_type_expert_typewise_meta_removal.log`에 저장합니다.
- 이번 후보 비교 단계에서는 80~100% Test를 추론하지 않습니다.

## 1. 설정, 경로 탐색과 실행 로그

저장소 루트 또는 `notebooks/` 어디서 실행해도 같은 원본 파일과 로그 경로를 사용합니다.

In [1]:
import gc
import hashlib
import json
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import sklearn
import xgboost
from IPython.display import Markdown, display
from sklearn.compose import ColumnTransformer
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBClassifier

EXPERIMENT_ID = "0825_peace_017_type_expert_typewise_meta_removal"
RANDOM_STATE = 42
TARGET = "class"
TIME_COLUMN = "timestamp"
TYPE_COLUMN = "inspection_type"
RECORD_ID = "record_id"
DECISION_THRESHOLD = 0.5
MIN_RECALL = 0.99
TRAIN_END_FRACTION = 0.70
VALIDATION_END_FRACTION = 0.80
BASELINE_004_WALK = {"fixed_0.5": {"mean_pr_auc": 0.06456566580859706, "mean_recall": 0.08378869542899249, "min_recall": 0.039473684210526314, "recall_99_folds": 0, "mean_false_call_reduction": 0.997159476859665}, "global_threshold": {"mean_pr_auc": 0.06456566580859706, "mean_recall": 0.9692982456140351, "min_recall": 0.9078947368421053, "recall_99_folds": 2, "mean_false_call_reduction": 0.16944884398683502}, "type_specific_thresholds": {"mean_pr_auc": 0.06456566580859706, "mean_recall": 0.9236895920783553, "min_recall": 0.7894736842105263, "recall_99_folds": 1, "mean_false_call_reduction": 0.33363103162699187}}
BASELINE_004_VALIDATION = {"fixed_0.5": {"pr_auc": 0.4496564930298315, "recall": 0.42296918767507, "false_call_reduction": 0.995809384231377, "tp": 151, "fn": 206, "fp": 183, "tn": 43486}, "global_threshold": {"pr_auc": 0.4496564930298315, "recall": 0.9915966386554622, "false_call_reduction": 0.6993977421053836, "tp": 354, "fn": 3, "fp": 13127, "tn": 30542}, "type_specific_thresholds": {"pr_auc": 0.4496564930298315, "recall": 0.9943977591036415, "false_call_reduction": 0.5644965536192722, "tp": 355, "fn": 2, "fp": 19018, "tn": 24651}}

XGB_PARAMS = {
    "objective": "binary:logistic",
    "eval_metric": "aucpr",
    "tree_method": "hist",
    "n_estimators": 400,
    "learning_rate": 0.05,
    "max_depth": 5,
    "min_child_weight": 10,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.1,
    "reg_lambda": 5.0,
    "max_delta_step": 1.0,
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
    "verbosity": 0,
}


def find_repo_root() -> Path:
    for candidate in [Path.cwd(), *Path.cwd().parents]:
        if (candidate / "AGENTS.md").exists() and (candidate / "notebooks").is_dir():
            return candidate.resolve()
    raise FileNotFoundError("AGENTS.md가 있는 저장소 루트를 찾지 못했습니다.")


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def find_data_pair(repo_root: Path) -> tuple[Path, Path]:
    candidates = [
        repo_root / "data" / "raw",
        repo_root.parent,
        Path.cwd(),
        Path.cwd().parent,
        Path.cwd().parent.parent,
    ]
    checked = set()
    for directory in candidates:
        resolved = directory.resolve()
        if resolved in checked:
            continue
        checked.add(resolved)
        data_path = resolved / "dataset.csv"
        mapping_path = resolved / "mapping.json"
        if data_path.exists() and mapping_path.exists():
            return data_path, mapping_path
    raise FileNotFoundError("dataset.csv와 mapping.json 쌍을 찾지 못했습니다.")


def safe_float(value):
    if isinstance(value, (np.floating, float)):
        return float(value)
    if isinstance(value, (np.integer, int)):
        return int(value)
    return value


def to_builtin_dict(value):
    if isinstance(value, dict):
        return {str(k): to_builtin_dict(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_builtin_dict(v) for v in value]
    if isinstance(value, tuple):
        return [to_builtin_dict(v) for v in value]
    return safe_float(value)


REPO_ROOT = find_repo_root()
DATA_PATH, MAPPING_PATH = find_data_pair(REPO_ROOT)
LOG_DIR = REPO_ROOT / "docs" / "peace"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / f"{EXPERIMENT_ID}.log"

logger = logging.getLogger(EXPERIMENT_ID)
logger.setLevel(logging.INFO)
logger.handlers.clear()
formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
file_handler = logging.FileHandler(LOG_PATH, mode="w", encoding="utf-8")
file_handler.setFormatter(formatter)
stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setFormatter(formatter)
logger.addHandler(file_handler)
logger.addHandler(stream_handler)
logger.propagate = False

DATA_SHA256_BEFORE = sha256_file(DATA_PATH)
MAPPING_SHA256_BEFORE = sha256_file(MAPPING_PATH)
logger.info("experiment=%s", EXPERIMENT_ID)
logger.info(
    "random_state=%d baseline_threshold=%.2f min_recall=%.2f",
    RANDOM_STATE,
    DECISION_THRESHOLD,
    MIN_RECALL,
)
logger.info("data_file=%s sha256=%s", DATA_PATH.name, DATA_SHA256_BEFORE)
logger.info("mapping_file=%s sha256=%s", MAPPING_PATH.name, MAPPING_SHA256_BEFORE)
logger.info(
    "versions python=%s pandas=%s sklearn=%s xgboost=%s",
    sys.version.split()[0], pd.__version__, sklearn.__version__, xgboost.__version__
)
logger.info("log_file=docs/peace/%s", LOG_PATH.name)
print("log saved to:", LOG_PATH.relative_to(REPO_ROOT))

2026-08-25 16:30:32,237 | INFO | experiment=0825_peace_017_type_expert_typewise_meta_removal

2026-08-25 16:30:32,238 | INFO | random_state=42 baseline_threshold=0.50 min_recall=0.99

2026-08-25 16:30:32,238 | INFO | data_file=dataset.csv sha256=53e8568743216d556856ed69b388f6750fbfa0b8c59ad31f970515ac9eb10e62

2026-08-25 16:30:32,239 | INFO | mapping_file=mapping.json sha256=3b20f440b6d9ed0baefa662e1a6f03688befbe0f28341a3b54655d3058c6e486

2026-08-25 16:30:32,239 | INFO | versions python=3.12.7 pandas=2.2.2 sklearn=1.5.1 xgboost=3.4.1

2026-08-25 16:30:32,239 | INFO | log_file=docs/peace/0825_peace_017_type_expert_typewise_meta_removal.log

log saved to: docs/peace/0825_peace_017_type_expert_typewise_meta_removal.log

## 2. 원본 데이터와 매핑 검증

첫 번째 익명 인덱스 열은 `record_id`로 이름만 바꾸며 원본 파일은 수정하지 않습니다.

In [2]:
raw_df = pd.read_csv(DATA_PATH, low_memory=False)
source_index_column = raw_df.columns[0]
if source_index_column.startswith("Unnamed:") or source_index_column == "":
    raw_df = raw_df.rename(columns={source_index_column: RECORD_ID})
elif source_index_column != RECORD_ID:
    raise ValueError(f"예상하지 못한 첫 번째 컬럼: {source_index_column}")

with MAPPING_PATH.open(encoding="utf-8") as stream:
    feature_mapping = json.load(stream)

required_columns = {RECORD_ID, TIME_COLUMN, TYPE_COLUMN, TARGET}
missing_required = required_columns - set(raw_df.columns)
assert not missing_required, f"필수 컬럼 누락: {sorted(missing_required)}"
assert len(raw_df) == 440_274
assert raw_df[RECORD_ID].is_unique
assert set(raw_df[TARGET].unique()) == {0, 1}
assert raw_df[TARGET].value_counts().to_dict() == {0: 435_652, 1: 4_622}
assert set(raw_df[TYPE_COLUMN].unique()) == {0, 1, 2, 3, 4}
assert set(feature_mapping) == {"0", "1", "2", "3", "4"}

raw_df[TIME_COLUMN] = pd.to_datetime(raw_df[TIME_COLUMN], errors="raise", utc=True)
raw_df = raw_df.sort_values([TIME_COLUMN, RECORD_ID], kind="stable").reset_index(drop=True)
inspection_columns = [column for column in raw_df.columns if column.startswith("inspection_feat")]
mapped_union = set().union(*(set(columns) for columns in feature_mapping.values()))
assert len(inspection_columns) == 70
assert len(mapped_union) == 65
assert mapped_union <= set(inspection_columns)

numeric_inputs = raw_df.select_dtypes(include=[np.number]).drop(columns=[TARGET, RECORD_ID])
assert np.isfinite(numeric_inputs.to_numpy()).all()

data_summary = pd.Series(
    {
        "rows": len(raw_df),
        "columns": raw_df.shape[1],
        "false_call_0": int((raw_df[TARGET] == 0).sum()),
        "real_defect_1": int((raw_df[TARGET] == 1).sum()),
        "real_defect_rate_pct": raw_df[TARGET].mean() * 100,
        "inspection_types": raw_df[TYPE_COLUMN].nunique(),
        "inspection_features": len(inspection_columns),
        "mapped_feature_union": len(mapped_union),
        "timestamp_start": raw_df[TIME_COLUMN].min(),
        "timestamp_end": raw_df[TIME_COLUMN].max(),
    },
    name="raw_data",
)
display(data_summary)
logger.info(
    "data_verified rows=%d columns=%d class_0=%d class_1=%d",
    len(raw_df), raw_df.shape[1], int((raw_df[TARGET] == 0).sum()), int((raw_df[TARGET] == 1).sum())
)

inspection_types = sorted(raw_df[TYPE_COLUMN].unique().tolist())
meta_columns = [column for column in raw_df.columns if column.startswith("meta_feat")]
mapped_feature_columns_by_type = {}
feature_columns_by_type = {}
feature_rows = []

for inspection_type in inspection_types:
    mapped_columns = feature_mapping[str(inspection_type)]
    assert len(mapped_columns) == len(set(mapped_columns))
    assert set(mapped_columns) <= set(raw_df.columns)
    mapped_feature_columns_by_type[inspection_type] = mapped_columns
    selected_columns = meta_columns + mapped_columns
    feature_columns_by_type[inspection_type] = selected_columns
    feature_rows.append(
        {
            "inspection_type": inspection_type,
            "meta_features": len(meta_columns),
            "mapped_inspection_features": len(mapped_columns),
            "total_model_features": len(selected_columns),
        }
    )

feature_summary = pd.DataFrame(feature_rows).set_index("inspection_type")
display(feature_summary)
logger.info("feature_mapping_verified=%s", feature_summary.to_dict(orient="index"))

rows                                       440274
columns                                        78
false_call_0                               435652
real_defect_1                                4622
real_defect_rate_pct                     1.049801
inspection_types                                5
inspection_features                            70
mapped_feature_union                           65
timestamp_start         1970-06-23 03:58:55+00:00
timestamp_end           1970-11-02 14:21:28+00:00
Name: raw_data, dtype: object

2026-08-25 16:30:36,639 | INFO | data_verified rows=440274 columns=78 class_0=435652 class_1=4622

,meta_features,mapped_inspection_features,total_model_features
inspection_type,,,
0,4,44,48
1,4,52,56
2,4,65,69
3,4,65,69
4,4,21,25

2026-08-25 16:30:36,644 | INFO | feature_mapping_verified={0: {'meta_features': 4, 'mapped_inspection_features': 44, 'total_model_features': 48}, 1: {'meta_features': 4, 'mapped_inspection_features': 52, 'total_model_features': 56}, 2: {'meta_features': 4, 'mapped_inspection_features': 65, 'total_model_features': 69}, 3: {'meta_features': 4, 'mapped_inspection_features': 65, 'total_model_features': 69}, 4: {'meta_features': 4, 'mapped_inspection_features': 21, 'total_model_features': 25}}

## 3. 시간순 분할과 평가 함수

004와 같은 시간순 70/10/20 분할을 유지하되, 이번 노트북은 70~80% Validation까지만 사용하고 마지막 20% Test는 건드리지 않습니다.

In [3]:
timestamp_group_sizes = raw_df.groupby(TIME_COLUMN, sort=True).size()
cumulative_rows = timestamp_group_sizes.cumsum().to_numpy()
timestamp_index = timestamp_group_sizes.index


def boundary_at(fraction: float):
    position = int(np.searchsorted(cumulative_rows, len(raw_df) * fraction, side="left"))
    return timestamp_index[position]


train_end_time = boundary_at(TRAIN_END_FRACTION)
validation_end_time = boundary_at(VALIDATION_END_FRACTION)
train_mask = raw_df[TIME_COLUMN] <= train_end_time
validation_mask = (
    (raw_df[TIME_COLUMN] > train_end_time)
    & (raw_df[TIME_COLUMN] <= validation_end_time)
)
test_mask = raw_df[TIME_COLUMN] > validation_end_time

train_df = raw_df.loc[train_mask].copy()
validation_df = raw_df.loc[validation_mask].copy()
test_df = raw_df.loc[test_mask].copy()
assert train_df[TIME_COLUMN].max() < validation_df[TIME_COLUMN].min()
assert validation_df[TIME_COLUMN].max() < test_df[TIME_COLUMN].min()
assert set(train_df[TIME_COLUMN]).isdisjoint(set(validation_df[TIME_COLUMN]))
assert set(validation_df[TIME_COLUMN]).isdisjoint(set(test_df[TIME_COLUMN]))

split_summary = pd.DataFrame(
    [
        {
            "split": "train",
            "rows": len(train_df),
            "positive_samples": int(train_df[TARGET].sum()),
            "positive_rate_pct": train_df[TARGET].mean() * 100,
            "timestamp_groups": train_df[TIME_COLUMN].nunique(),
            "start_time": train_df[TIME_COLUMN].min(),
            "end_time": train_df[TIME_COLUMN].max(),
        },
        {
            "split": "validation",
            "rows": len(validation_df),
            "positive_samples": int(validation_df[TARGET].sum()),
            "positive_rate_pct": validation_df[TARGET].mean() * 100,
            "timestamp_groups": validation_df[TIME_COLUMN].nunique(),
            "start_time": validation_df[TIME_COLUMN].min(),
            "end_time": validation_df[TIME_COLUMN].max(),
        },
        {
            "split": "test_holdout_unused",
            "rows": len(test_df),
            "positive_samples": int(test_df[TARGET].sum()),
            "positive_rate_pct": test_df[TARGET].mean() * 100,
            "timestamp_groups": test_df[TIME_COLUMN].nunique(),
            "start_time": test_df[TIME_COLUMN].min(),
            "end_time": test_df[TIME_COLUMN].max(),
        },
    ]
).set_index("split")
display(split_summary)
logger.info("split_summary=%s", split_summary.reset_index().to_dict(orient="records"))


def evaluate_predictions(y_true, prediction, probability):
    y_true = np.asarray(y_true, dtype=np.int8)
    prediction = np.asarray(prediction, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)
    tn, fp, fn, tp = confusion_matrix(y_true, prediction, labels=[0, 1]).ravel()
    has_both_classes = np.unique(y_true).size == 2
    has_positive = (tp + fn) > 0
    return {
        "rows": len(y_true),
        "positive_samples": int(y_true.sum()),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
        "accuracy": accuracy_score(y_true, prediction),
        "precision": precision_score(y_true, prediction, zero_division=0),
        "recall": recall_score(y_true, prediction, zero_division=0) if has_positive else np.nan,
        "false_call_reduction": tn / (tn + fp) if (tn + fp) else np.nan,
        "f1": f1_score(y_true, prediction, zero_division=0) if has_positive else np.nan,
        "roc_auc": roc_auc_score(y_true, probability) if has_both_classes else np.nan,
        "pr_auc": average_precision_score(y_true, probability) if has_both_classes else np.nan,
    }


def evaluate_probabilities(y_true, probability, threshold=DECISION_THRESHOLD):
    probability = np.asarray(probability, dtype=np.float64)
    prediction = (probability >= threshold).astype(np.int8)
    return evaluate_predictions(y_true, prediction, probability)


def select_threshold(y_true, probability, min_recall=MIN_RECALL):
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)
    if np.unique(y_true).size != 2:
        raise ValueError("임계값 선택에는 positive와 negative가 모두 필요합니다.")

    order = np.argsort(-probability, kind="stable")
    sorted_probability = probability[order]
    sorted_target = y_true[order]
    cumulative_tp = np.cumsum(sorted_target == 1)
    cumulative_fp = np.cumsum(sorted_target == 0)
    group_ends = np.flatnonzero(np.r_[sorted_probability[:-1] != sorted_probability[1:], True])

    thresholds = sorted_probability[group_ends]
    tp = cumulative_tp[group_ends]
    fp = cumulative_fp[group_ends]
    total_positive = int((y_true == 1).sum())
    total_negative = int((y_true == 0).sum())
    recall = tp / total_positive
    false_call_reduction = 1.0 - (fp / total_negative)
    feasible = np.flatnonzero(recall >= min_recall)
    if feasible.size == 0:
        raise RuntimeError(f"Recall {min_recall:.2%} 조건을 만족하는 threshold가 없습니다.")

    best_local = np.lexsort((thresholds[feasible], recall[feasible], false_call_reduction[feasible]))[-1]
    best = feasible[best_local]
    selected_threshold = float(thresholds[best])
    metrics = evaluate_probabilities(y_true, probability, selected_threshold)
    return {"threshold": selected_threshold, "min_recall": min_recall, **metrics}


_test_y = np.array([1, 0, 1, 0, 1, 0], dtype=np.int8)
_test_probability = np.array([0.9, 0.8, 0.7, 0.6, 0.4, 0.2])
_optimized = select_threshold(_test_y, _test_probability, min_recall=2 / 3)
_reference_rows = []
for _threshold in np.unique(_test_probability):
    _metrics = evaluate_probabilities(_test_y, _test_probability, _threshold)
    if _metrics["recall"] >= 2 / 3:
        _reference_rows.append((_metrics["false_call_reduction"], _metrics["recall"], _threshold))
_reference = max(_reference_rows)
assert np.isclose(_optimized["threshold"], _reference[2])
logger.info("threshold_selector_unit_test=PASS")


def make_preprocessor(feature_columns):
    categorical = [column for column in meta_columns if column in feature_columns]
    continuous = [column for column in feature_columns if column not in categorical]
    return ColumnTransformer(
        transformers=[
            (
                "categorical",
                OneHotEncoder(handle_unknown="ignore", dtype=np.float32),
                categorical,
            ),
            ("continuous", "passthrough", continuous),
        ],
        sparse_threshold=1.0,
        verbose_feature_names_out=True,
    )


def robust_stat_frame(reference_df):
    medians = reference_df.median(axis=0)
    abs_dev = reference_df.sub(medians, axis=1).abs()
    mad = abs_dev.median(axis=0)
    raw_scale = 1.4826 * mad
    scale = raw_scale.where(raw_scale > 0, 1.0).fillna(1.0)
    return pd.DataFrame({"median": medians, "mad": mad, "scale": scale})


WALK_FORWARD_SPECS = [
    {
        "fold": "fold_1",
        "train_start": 0.00,
        "train_end": 0.30,
        "calibration_start": 0.30,
        "calibration_end": 0.40,
        "evaluation_start": 0.40,
        "evaluation_end": 0.50,
    },
    {
        "fold": "fold_2",
        "train_start": 0.00,
        "train_end": 0.40,
        "calibration_start": 0.40,
        "calibration_end": 0.50,
        "evaluation_start": 0.50,
        "evaluation_end": 0.60,
    },
    {
        "fold": "fold_3",
        "train_start": 0.00,
        "train_end": 0.50,
        "calibration_start": 0.50,
        "calibration_end": 0.60,
        "evaluation_start": 0.60,
        "evaluation_end": 0.70,
    },
]

walk_forward_boundaries = {
    fraction: boundary_at(fraction)
    for fraction in [0.30, 0.40, 0.50, 0.60, 0.70]
}
walk_forward_segments = {}
walk_forward_split_rows = []

for spec in WALK_FORWARD_SPECS:
    fold_name = spec["fold"]
    train_end = walk_forward_boundaries[spec["train_end"]]
    calibration_start = walk_forward_boundaries[spec["calibration_start"]]
    calibration_end = walk_forward_boundaries[spec["calibration_end"]]
    evaluation_start = walk_forward_boundaries[spec["evaluation_start"]]
    evaluation_end = walk_forward_boundaries[spec["evaluation_end"]]

    segments = {
        "train": raw_df.loc[raw_df[TIME_COLUMN] <= train_end].copy(),
        "calibration": raw_df.loc[
            (raw_df[TIME_COLUMN] > calibration_start)
            & (raw_df[TIME_COLUMN] <= calibration_end)
        ].copy(),
        "evaluation": raw_df.loc[
            (raw_df[TIME_COLUMN] > evaluation_start)
            & (raw_df[TIME_COLUMN] <= evaluation_end)
        ].copy(),
    }
    assert segments["train"][TIME_COLUMN].max() < segments["calibration"][TIME_COLUMN].min()
    assert segments["calibration"][TIME_COLUMN].max() < segments["evaluation"][TIME_COLUMN].min()
    walk_forward_segments[fold_name] = segments

    for segment_name, frame in segments.items():
        walk_forward_split_rows.append(
            {
                "fold": fold_name,
                "segment": segment_name,
                "rows": len(frame),
                "positive_samples": int(frame[TARGET].sum()),
                "positive_rate_pct": frame[TARGET].mean() * 100,
                "timestamp_groups": frame[TIME_COLUMN].nunique(),
                "start_time": frame[TIME_COLUMN].min(),
                "end_time": frame[TIME_COLUMN].max(),
            }
        )

walk_forward_split_summary = pd.DataFrame(walk_forward_split_rows).set_index(["fold", "segment"])
display(walk_forward_split_summary)
logger.info(
    "walk_forward_split_summary=%s",
    walk_forward_split_summary.reset_index().to_dict(orient="records"),
)

,rows,positive_samples,positive_rate_pct,timestamp_groups,start_time,end_time
split,,,,,,
train,308196,1940,0.629470,29249,1970-06-23 03:58:55+00:00,1970-10-05 00:29:59+00:00
validation,44026,357,0.810884,3400,1970-10-05 00:30:30+00:00,1970-10-13 16:54:14+00:00
test_holdout_unused,88052,2325,2.640485,7093,1970-10-13 16:54:52+00:00,1970-11-02 14:21:28+00:00

2026-08-25 16:30:37,036 | INFO | split_summary=[{'split': 'train', 'rows': 308196, 'positive_samples': 1940, 'positive_rate_pct': 0.6294695583330089, 'timestamp_groups': 29249, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-10-05 00:29:59+0000', tz='UTC')}, {'split': 'validation', 'rows': 44026, 'positive_samples': 357, 'positive_rate_pct': 0.8108844773542907, 'timestamp_groups': 3400, 'start_time': Timestamp('1970-10-05 00:30:30+0000', tz='UTC'), 'end_time': Timestamp('1970-10-13 16:54:14+0000', tz='UTC')}, {'split': 'test_holdout_unused', 'rows': 88052, 'positive_samples': 2325, 'positive_rate_pct': 2.640485167855358, 'timestamp_groups': 7093, 'start_time': Timestamp('1970-10-13 16:54:52+0000', tz='UTC'), 'end_time': Timestamp('1970-11-02 14:21:28+0000', tz='UTC')}]

2026-08-25 16:30:37,054 | INFO | threshold_selector_unit_test=PASS

                      rows  positive_samples  positive_rate_pct  \
fold   segment
fold_1 train        132137              1223           0.925555
       calibration   43979               200           0.454763
       evaluation    44040               326           0.740236
fold_2 train        176116              1423           0.807990
       calibration   44040               326           0.740236
       evaluation    44187               152           0.343993
fold_3 train        220156              1749           0.794437
       calibration   44187               152           0.343993
       evaluation    43853                39           0.088933

                    timestamp_groups                start_time  \
fold   segment
fold_1 train                   15230 1970-06-23 03:58:55+00:00
       calibration              1251 1970-08-18 06:51:41+00:00
       evaluation               5415 1970-08-21 23:33:55+00:00
fold_2 train                   16481 1970-06-23 03:58:55+00:00
       calibration              5415 1970-08-21 23:33:55+00:00
       evaluation               4167 1970-09-15 06:47:13+00:00
fold_3 train                   21896 1970-06-23 03:58:55+00:00
       calibration              4167 1970-09-15 06:47:13+00:00
       evaluation               3186 1970-09-28 05:11:13+00:00

                                    end_time
fold   segment
fold_1 train       1970-08-18 06:51:10+00:00
       calibration 1970-08-21 23:32:59+00:00
       evaluation  1970-09-15 06:46:33+00:00
fold_2 train       1970-08-21 23:32:59+00:00
       calibration 1970-09-15 06:46:33+00:00
       evaluation  1970-09-28 05:10:37+00:00
fold_3 train       1970-09-15 06:46:33+00:00
       calibration 1970-09-28 05:10:37+00:00
       evaluation  1970-10-05 00:29:59+00:00

2026-08-25 16:30:37,236 | INFO | walk_forward_split_summary=[{'fold': 'fold_1', 'segment': 'train', 'rows': 132137, 'positive_samples': 1223, 'positive_rate_pct': 0.9255545380930399, 'timestamp_groups': 15230, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-08-18 06:51:10+0000', tz='UTC')}, {'fold': 'fold_1', 'segment': 'calibration', 'rows': 43979, 'positive_samples': 200, 'positive_rate_pct': 0.4547625002842266, 'timestamp_groups': 1251, 'start_time': Timestamp('1970-08-18 06:51:41+0000', tz='UTC'), 'end_time': Timestamp('1970-08-21 23:32:59+0000', tz='UTC')}, {'fold': 'fold_1', 'segment': 'evaluation', 'rows': 44040, 'positive_samples': 326, 'positive_rate_pct': 0.740236148955495, 'timestamp_groups': 5415, 'start_time': Timestamp('1970-08-21 23:33:55+0000', tz='UTC'), 'end_time': Timestamp('1970-09-15 06:46:33+0000', tz='UTC')}, {'fold': 'fold_2', 'segment': 'train', 'rows': 176116, 'positive_samples': 1423, 'positive_rate_pct': 0.8079901882849939, 'timestamp_groups': 16481, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-08-21 23:32:59+0000', tz='UTC')}, {'fold': 'fold_2', 'segment': 'calibration', 'rows': 44040, 'positive_samples': 326, 'positive_rate_pct': 0.740236148955495, 'timestamp_groups': 5415, 'start_time': Timestamp('1970-08-21 23:33:55+0000', tz='UTC'), 'end_time': Timestamp('1970-09-15 06:46:33+0000', tz='UTC')}, {'fold': 'fold_2', 'segment': 'evaluation', 'rows': 44187, 'positive_samples': 152, 'positive_rate_pct': 0.34399257700228575, 'timestamp_groups': 4167, 'start_time': Timestamp('1970-09-15 06:47:13+0000', tz='UTC'), 'end_time': Timestamp('1970-09-28 05:10:37+0000', tz='UTC')}, {'fold': 'fold_3', 'segment': 'train', 'rows': 220156, 'positive_samples': 1749, 'positive_rate_pct': 0.7944366721779101, 'timestamp_groups': 21896, 'start_time': Timestamp('1970-06-23 03:58:55+0000', tz='UTC'), 'end_time': Timestamp('1970-09-15 06:46:33+0000', tz='UTC')}, {'fold': 'fold_3', 'segment': 'calibration', 'rows': 44187, 'positive_samples': 152, 'positive_rate_pct': 0.34399257700228575, 'timestamp_groups': 4167, 'start_time': Timestamp('1970-09-15 06:47:13+0000', tz='UTC'), 'end_time': Timestamp('1970-09-28 05:10:37+0000', tz='UTC')}, {'fold': 'fold_3', 'segment': 'evaluation', 'rows': 43853, 'positive_samples': 39, 'positive_rate_pct': 0.08893348231591909, 'timestamp_groups': 3186, 'start_time': Timestamp('1970-09-28 05:11:13+0000', tz='UTC'), 'end_time': Timestamp('1970-10-05 00:29:59+0000', tz='UTC')}]

## 4. 타입별 Meta Feature ablation

각 타입에서 `with_meta`와 `without_meta`를 동일한 Walk-forward fold로 비교하고, Walk-forward 결과만으로 타입별 구성을 선택합니다.

In [4]:
VARIANT_NAMES = ["with_meta", "without_meta"]
feature_columns_by_type_variant = {
    inspection_type: {
        "with_meta": feature_columns_by_type[inspection_type],
        "without_meta": mapped_feature_columns_by_type[inspection_type],
    }
    for inspection_type in inspection_types
}
variant_feature_summary = pd.DataFrame(
    [
        {
            "inspection_type": inspection_type,
            "variant": variant_name,
            "raw_features": len(feature_columns),
        }
        for inspection_type in inspection_types
        for variant_name, feature_columns in feature_columns_by_type_variant[inspection_type].items()
    ]
).set_index(["inspection_type", "variant"])
display(variant_feature_summary)


def fit_variant_probabilities(train_frame, calibration_frame, evaluation_frame, fold_name):
    probability_store = {"calibration": {}, "evaluation": {}}
    variant_metric_rows = []
    training_rows = []

    for inspection_type in inspection_types:
        type_train = train_frame.loc[train_frame[TYPE_COLUMN] == inspection_type].copy()
        type_calibration = calibration_frame.loc[calibration_frame[TYPE_COLUMN] == inspection_type].copy()
        type_evaluation = evaluation_frame.loc[evaluation_frame[TYPE_COLUMN] == inspection_type].copy()
        y_train = type_train[TARGET].astype("int8")

        assert len(type_train) > 0
        assert len(type_calibration) > 0
        assert len(type_evaluation) > 0
        assert y_train.nunique() == 2
        assert type_calibration[TARGET].nunique() == 2
        assert type_train[TIME_COLUMN].max() < type_calibration[TIME_COLUMN].min()
        assert type_calibration[TIME_COLUMN].max() < type_evaluation[TIME_COLUMN].min()

        for variant_name in VARIANT_NAMES:
            feature_columns = feature_columns_by_type_variant[inspection_type][variant_name]
            preprocessor = make_preprocessor(feature_columns)
            X_train = preprocessor.fit_transform(type_train[feature_columns])
            X_calibration = preprocessor.transform(type_calibration[feature_columns])
            X_evaluation = preprocessor.transform(type_evaluation[feature_columns])

            model = XGBClassifier(**XGB_PARAMS)
            model.fit(X_train, y_train, verbose=False)
            calibration_probability = pd.Series(
                model.predict_proba(X_calibration)[:, 1],
                index=type_calibration.index,
                dtype="float64",
            )
            evaluation_probability = pd.Series(
                model.predict_proba(X_evaluation)[:, 1],
                index=type_evaluation.index,
                dtype="float64",
            )
            probability_store["calibration"][(inspection_type, variant_name)] = calibration_probability
            probability_store["evaluation"][(inspection_type, variant_name)] = evaluation_probability

            selection = select_threshold(type_calibration[TARGET], calibration_probability, min_recall=MIN_RECALL)
            thresholded_metrics = evaluate_predictions(
                type_evaluation[TARGET],
                (evaluation_probability >= selection["threshold"]).astype("int8"),
                evaluation_probability,
            )
            base_metrics = evaluate_probabilities(type_evaluation[TARGET], evaluation_probability, DECISION_THRESHOLD)
            variant_metric_rows.append(
                {
                    "fold": fold_name,
                    "inspection_type": inspection_type,
                    "variant": variant_name,
                    "calibration_threshold": selection["threshold"],
                    "pr_auc": base_metrics["pr_auc"],
                    "roc_auc": base_metrics["roc_auc"],
                    "fixed_recall": base_metrics["recall"],
                    "fixed_false_call_reduction": base_metrics["false_call_reduction"],
                    "thresholded_recall": thresholded_metrics["recall"],
                    "thresholded_false_call_reduction": thresholded_metrics["false_call_reduction"],
                    "tp": thresholded_metrics["tp"],
                    "fn": thresholded_metrics["fn"],
                    "fp": thresholded_metrics["fp"],
                    "tn": thresholded_metrics["tn"],
                    "raw_features": len(feature_columns),
                    "encoded_features": X_train.shape[1],
                }
            )
            training_rows.append(
                {
                    "fold": fold_name,
                    "inspection_type": inspection_type,
                    "variant": variant_name,
                    "train_rows": len(type_train),
                    "train_positive": int(y_train.sum()),
                    "calibration_rows": len(type_calibration),
                    "evaluation_rows": len(type_evaluation),
                    "raw_features": len(feature_columns),
                    "encoded_features": X_train.shape[1],
                }
            )
            logger.info(
                "walk_forward_variant_fit_done fold=%s type=%d variant=%s raw_features=%d",
                fold_name,
                inspection_type,
                variant_name,
                len(feature_columns),
            )
            del preprocessor, model, X_train, X_calibration, X_evaluation
            gc.collect()

    return probability_store, variant_metric_rows, training_rows


probability_store_by_fold = {}
variant_metric_rows = []
walk_forward_training_rows = []

for spec in WALK_FORWARD_SPECS:
    fold_name = spec["fold"]
    segments = walk_forward_segments[fold_name]
    probability_store, fold_variant_metric_rows, training_rows = fit_variant_probabilities(
        segments["train"], segments["calibration"], segments["evaluation"], fold_name
    )
    probability_store_by_fold[fold_name] = probability_store
    variant_metric_rows.extend(fold_variant_metric_rows)
    walk_forward_training_rows.extend(training_rows)

variant_metrics = pd.DataFrame(variant_metric_rows)
variant_summary = (
    variant_metrics.groupby(["inspection_type", "variant"])
    .agg(
        folds=("fold", "nunique"),
        mean_pr_auc=("pr_auc", "mean"),
        mean_roc_auc=("roc_auc", "mean"),
        mean_fixed_recall=("fixed_recall", "mean"),
        mean_thresholded_recall=("thresholded_recall", "mean"),
        mean_thresholded_false_call_reduction=("thresholded_false_call_reduction", "mean"),
        mean_encoded_features=("encoded_features", "mean"),
    )
    .reset_index()
)
display(variant_metrics)
display(variant_summary)

selected_variant_by_type = {}
selection_rows = []
for inspection_type in inspection_types:
    subset = variant_summary.loc[variant_summary["inspection_type"] == inspection_type].copy()
    subset = subset.sort_values(
        by=[
            "mean_pr_auc",
            "mean_thresholded_recall",
            "mean_thresholded_false_call_reduction",
            "mean_roc_auc",
        ],
        ascending=False,
        kind="stable",
    )
    best = subset.iloc[0]
    selected_variant_by_type[inspection_type] = best["variant"]
    selection_rows.append(
        {
            "inspection_type": inspection_type,
            "selected_variant": best["variant"],
            "mean_pr_auc": best["mean_pr_auc"],
            "mean_thresholded_recall": best["mean_thresholded_recall"],
            "mean_thresholded_false_call_reduction": best["mean_thresholded_false_call_reduction"],
            "mean_encoded_features": best["mean_encoded_features"],
        }
    )

selected_variant_summary = pd.DataFrame(selection_rows).set_index("inspection_type")
display(selected_variant_summary)
logger.info("selected_variant_by_type=%s", selected_variant_by_type)

walk_forward_threshold_rows = []
walk_forward_metric_rows = []
walk_forward_type_evaluation_rows = []

for spec in WALK_FORWARD_SPECS:
    fold_name = spec["fold"]
    segments = walk_forward_segments[fold_name]
    calibration_frame = segments["calibration"]
    evaluation_frame = segments["evaluation"]
    calibration_probability = pd.Series(np.nan, index=calibration_frame.index, dtype="float64")
    evaluation_probability = pd.Series(np.nan, index=evaluation_frame.index, dtype="float64")

    for inspection_type in inspection_types:
        variant_name = selected_variant_by_type[inspection_type]
        calibration_probability.loc[
            calibration_frame.index.intersection(
                probability_store_by_fold[fold_name]["calibration"][(inspection_type, variant_name)].index
            )
        ] = probability_store_by_fold[fold_name]["calibration"][(inspection_type, variant_name)]
        evaluation_probability.loc[
            evaluation_frame.index.intersection(
                probability_store_by_fold[fold_name]["evaluation"][(inspection_type, variant_name)].index
            )
        ] = probability_store_by_fold[fold_name]["evaluation"][(inspection_type, variant_name)]

    assert calibration_probability.notna().all()
    assert evaluation_probability.notna().all()

    global_selection = select_threshold(calibration_frame[TARGET], calibration_probability, min_recall=MIN_RECALL)
    walk_forward_threshold_rows.append({"fold": fold_name, "scope": "global", **global_selection})

    type_evaluation_prediction = pd.Series(np.nan, index=evaluation_frame.index, dtype="float64")
    for inspection_type in inspection_types:
        variant_name = selected_variant_by_type[inspection_type]
        type_calibration = calibration_frame.loc[calibration_frame[TYPE_COLUMN] == inspection_type]
        type_calibration_probability = probability_store_by_fold[fold_name]["calibration"][(inspection_type, variant_name)]
        selection = select_threshold(type_calibration[TARGET], type_calibration_probability, min_recall=MIN_RECALL)
        threshold = selection["threshold"]
        walk_forward_threshold_rows.append({"fold": fold_name, "scope": f"type_{inspection_type}", **selection})

        type_evaluation = evaluation_frame.loc[evaluation_frame[TYPE_COLUMN] == inspection_type]
        type_evaluation_probability = probability_store_by_fold[fold_name]["evaluation"][(inspection_type, variant_name)]
        type_prediction = (type_evaluation_probability >= threshold).astype("int8")
        type_evaluation_prediction.loc[type_evaluation.index] = type_prediction
        type_metrics = evaluate_predictions(type_evaluation[TARGET], type_prediction, type_evaluation_probability)
        type_metrics.update({"fold": fold_name, "inspection_type": inspection_type, "threshold": threshold})
        walk_forward_type_evaluation_rows.append(type_metrics)

    strategy_metrics = {
        "fixed_0.5": evaluate_probabilities(evaluation_frame[TARGET], evaluation_probability, DECISION_THRESHOLD),
        "global_threshold": evaluate_probabilities(evaluation_frame[TARGET], evaluation_probability, global_selection["threshold"]),
        "type_specific_thresholds": evaluate_predictions(evaluation_frame[TARGET], type_evaluation_prediction, evaluation_probability),
    }
    for strategy, metrics in strategy_metrics.items():
        walk_forward_metric_rows.append({"fold": fold_name, "strategy": strategy, **metrics})

walk_forward_threshold_summary = pd.DataFrame(walk_forward_threshold_rows).set_index(["fold", "scope"])
walk_forward_evaluation_metrics = pd.DataFrame(walk_forward_metric_rows).set_index(["fold", "strategy"])
walk_forward_type_evaluation = pd.DataFrame(walk_forward_type_evaluation_rows).set_index(["fold", "inspection_type"])
walk_forward_training_summary = pd.DataFrame(walk_forward_training_rows).set_index(["fold", "inspection_type", "variant"])

display(walk_forward_threshold_summary[["threshold", "positive_samples", "recall", "false_call_reduction", "tp", "fn"]])
display(walk_forward_evaluation_metrics[["positive_samples", "pr_auc", "precision", "recall", "false_call_reduction", "f1", "tp", "fn", "fp", "tn"]])
display(walk_forward_type_evaluation[["threshold", "positive_samples", "pr_auc", "recall", "false_call_reduction", "tp", "fn"]])

walk_forward_strategy_summary = (
    walk_forward_evaluation_metrics.reset_index()
    .groupby("strategy")
    .agg(
        folds=("fold", "nunique"),
        mean_pr_auc=("pr_auc", "mean"),
        mean_recall=("recall", "mean"),
        min_recall=("recall", "min"),
        recall_99_folds=("recall", lambda values: int((values >= MIN_RECALL).sum())),
        mean_false_call_reduction=("false_call_reduction", "mean"),
        min_false_call_reduction=("false_call_reduction", "min"),
        total_tp=("tp", "sum"),
        total_fn=("fn", "sum"),
    )
)
display(walk_forward_strategy_summary)
display(walk_forward_training_summary)
logger.info("walk_forward_strategy_summary=%s", walk_forward_strategy_summary.to_dict(orient="index"))

pooled_probability = pd.Series(np.nan, index=validation_df.index, dtype="float64")
type_metric_rows = []
training_rows = []

for inspection_type in inspection_types:
    variant_name = selected_variant_by_type[inspection_type]
    feature_columns = feature_columns_by_type_variant[inspection_type][variant_name]
    type_train = train_df.loc[train_df[TYPE_COLUMN] == inspection_type].copy()
    type_validation = validation_df.loc[validation_df[TYPE_COLUMN] == inspection_type].copy()
    y_train = type_train[TARGET].astype("int8")

    assert len(type_train) > 0 and len(type_validation) > 0
    assert y_train.nunique() == 2
    assert type_train[TIME_COLUMN].max() < type_validation[TIME_COLUMN].min()

    preprocessor = make_preprocessor(feature_columns)
    X_train = preprocessor.fit_transform(type_train[feature_columns])
    X_validation = preprocessor.transform(type_validation[feature_columns])

    model = XGBClassifier(**XGB_PARAMS)
    model.fit(X_train, y_train, verbose=False)
    probability = model.predict_proba(X_validation)[:, 1]
    pooled_probability.loc[type_validation.index] = probability

    metrics = evaluate_probabilities(type_validation[TARGET], probability)
    metrics["inspection_type"] = inspection_type
    type_metric_rows.append(metrics)
    training_rows.append(
        {
            "inspection_type": inspection_type,
            "selected_variant": variant_name,
            "train_rows": len(type_train),
            "train_positive": int(y_train.sum()),
            "validation_rows": len(type_validation),
            "validation_positive": int(type_validation[TARGET].sum()),
            "raw_features": len(feature_columns),
            "encoded_features": X_train.shape[1],
            "trees": model.n_estimators,
        }
    )
    logger.info("validation_fit_done type=%d variant=%s", inspection_type, variant_name)
    del X_train, X_validation, probability, model, preprocessor
    gc.collect()

assert pooled_probability.notna().all()
pooled_metrics = pd.Series(evaluate_probabilities(validation_df[TARGET], pooled_probability), name="type_expert_validation")
type_metrics = pd.DataFrame(type_metric_rows).set_index("inspection_type")
training_summary = pd.DataFrame(training_rows).set_index("inspection_type")
count_columns = ["rows", "positive_samples", "tn", "fp", "fn", "tp"]
type_metrics[count_columns] = type_metrics[count_columns].astype("int64")

display(pooled_metrics)
display(type_metrics[["rows", "positive_samples", "pr_auc", "roc_auc", "accuracy", "precision", "recall", "false_call_reduction", "f1", "tp", "fn", "fp", "tn"]])
display(training_summary)

global_threshold_selection = select_threshold(validation_df[TARGET], pooled_probability, min_recall=MIN_RECALL)
thresholds_by_type = {}
type_threshold_rows = []
type_validation_prediction = pd.Series(np.nan, index=validation_df.index, dtype="float64")

for inspection_type in inspection_types:
    type_validation = validation_df.loc[validation_df[TYPE_COLUMN] == inspection_type]
    type_probability = pooled_probability.loc[type_validation.index]
    selection = select_threshold(type_validation[TARGET], type_probability, min_recall=MIN_RECALL)
    thresholds_by_type[inspection_type] = selection["threshold"]
    selection["inspection_type"] = inspection_type
    type_threshold_rows.append(selection)
    type_validation_prediction.loc[type_validation.index] = (type_probability >= selection["threshold"]).astype("int8")

type_threshold_selection = pd.DataFrame(type_threshold_rows).set_index("inspection_type")
global_validation_metrics = pd.Series(
    evaluate_probabilities(validation_df[TARGET], pooled_probability, global_threshold_selection["threshold"]),
    name="global_threshold",
)
type_specific_validation_metrics = pd.Series(
    evaluate_predictions(validation_df[TARGET], type_validation_prediction, pooled_probability),
    name="type_specific_thresholds",
)
validation_strategy_metrics = pd.DataFrame(
    {
        "fixed_0.5": pooled_metrics,
        "global_threshold": global_validation_metrics,
        "type_specific_thresholds": type_specific_validation_metrics,
    }
).T
threshold_summary = pd.concat(
    [
        pd.DataFrame([{"scope": "global", **global_threshold_selection}]).set_index("scope"),
        type_threshold_selection.rename_axis("scope"),
    ],
    axis=0,
)
display(threshold_summary[["threshold", "positive_samples", "recall", "false_call_reduction", "tp", "fn", "fp", "tn"]])
display(validation_strategy_metrics[["pr_auc", "precision", "recall", "false_call_reduction", "f1", "tp", "fn", "fp", "tn"]])
logger.info("validation_strategy_metrics=%s", validation_strategy_metrics.to_dict(orient="index"))

                              raw_features
inspection_type variant
0               with_meta               48
                without_meta            44
1               with_meta               56
                without_meta            52
2               with_meta               69
                without_meta            65
3               with_meta               69
                without_meta            65
4               with_meta               25
                without_meta            21

2026-08-25 16:30:37,650 | INFO | walk_forward_variant_fit_done fold=fold_1 type=0 variant=with_meta raw_features=48

2026-08-25 16:30:37,962 | INFO | walk_forward_variant_fit_done fold=fold_1 type=0 variant=without_meta raw_features=44

2026-08-25 16:30:38,657 | INFO | walk_forward_variant_fit_done fold=fold_1 type=1 variant=with_meta raw_features=56

2026-08-25 16:30:39,517 | INFO | walk_forward_variant_fit_done fold=fold_1 type=1 variant=without_meta raw_features=52

2026-08-25 16:30:40,381 | INFO | walk_forward_variant_fit_done fold=fold_1 type=2 variant=with_meta raw_features=69

2026-08-25 16:30:41,506 | INFO | walk_forward_variant_fit_done fold=fold_1 type=2 variant=without_meta raw_features=65

2026-08-25 16:30:42,437 | INFO | walk_forward_variant_fit_done fold=fold_1 type=3 variant=with_meta raw_features=69

2026-08-25 16:30:43,768 | INFO | walk_forward_variant_fit_done fold=fold_1 type=3 variant=without_meta raw_features=65

2026-08-25 16:30:44,236 | INFO | walk_forward_variant_fit_done fold=fold_1 type=4 variant=with_meta raw_features=25

2026-08-25 16:30:44,345 | INFO | walk_forward_variant_fit_done fold=fold_1 type=4 variant=without_meta raw_features=21

2026-08-25 16:30:45,337 | INFO | walk_forward_variant_fit_done fold=fold_2 type=0 variant=with_meta raw_features=48

2026-08-25 16:30:46,031 | INFO | walk_forward_variant_fit_done fold=fold_2 type=0 variant=without_meta raw_features=44

2026-08-25 16:30:46,601 | INFO | walk_forward_variant_fit_done fold=fold_2 type=1 variant=with_meta raw_features=56

2026-08-25 16:30:47,685 | INFO | walk_forward_variant_fit_done fold=fold_2 type=1 variant=without_meta raw_features=52

2026-08-25 16:30:48,789 | INFO | walk_forward_variant_fit_done fold=fold_2 type=2 variant=with_meta raw_features=69

2026-08-25 16:30:49,930 | INFO | walk_forward_variant_fit_done fold=fold_2 type=2 variant=without_meta raw_features=65

2026-08-25 16:30:51,049 | INFO | walk_forward_variant_fit_done fold=fold_2 type=3 variant=with_meta raw_features=69

2026-08-25 16:30:52,256 | INFO | walk_forward_variant_fit_done fold=fold_2 type=3 variant=without_meta raw_features=65

2026-08-25 16:30:52,543 | INFO | walk_forward_variant_fit_done fold=fold_2 type=4 variant=with_meta raw_features=25

2026-08-25 16:30:52,661 | INFO | walk_forward_variant_fit_done fold=fold_2 type=4 variant=without_meta raw_features=21

2026-08-25 16:30:53,968 | INFO | walk_forward_variant_fit_done fold=fold_3 type=0 variant=with_meta raw_features=48

2026-08-25 16:30:54,709 | INFO | walk_forward_variant_fit_done fold=fold_3 type=0 variant=without_meta raw_features=44

2026-08-25 16:30:55,651 | INFO | walk_forward_variant_fit_done fold=fold_3 type=1 variant=with_meta raw_features=56

2026-08-25 16:30:56,371 | INFO | walk_forward_variant_fit_done fold=fold_3 type=1 variant=without_meta raw_features=52

2026-08-25 16:30:57,944 | INFO | walk_forward_variant_fit_done fold=fold_3 type=2 variant=with_meta raw_features=69

2026-08-25 16:30:59,914 | INFO | walk_forward_variant_fit_done fold=fold_3 type=2 variant=without_meta raw_features=65

2026-08-25 16:31:01,285 | INFO | walk_forward_variant_fit_done fold=fold_3 type=3 variant=with_meta raw_features=69

2026-08-25 16:31:02,709 | INFO | walk_forward_variant_fit_done fold=fold_3 type=3 variant=without_meta raw_features=65

2026-08-25 16:31:02,856 | INFO | walk_forward_variant_fit_done fold=fold_3 type=4 variant=with_meta raw_features=25

2026-08-25 16:31:02,974 | INFO | walk_forward_variant_fit_done fold=fold_3 type=4 variant=without_meta raw_features=21

,fold,inspection_type,variant,calibration_threshold,pr_auc,roc_auc,fixed_recall,fixed_false_call_reduction,thresholded_recall,thresholded_false_call_reduction,tp,fn,fp,tn,raw_features,encoded_features
0,fold_1,0,with_meta,0.002342,0.022766,0.772963,0.000000,1.000000,0.940000,0.681663,47,3,2052,4394,48,80
1,fold_1,0,without_meta,0.001523,0.014722,0.638678,0.000000,1.000000,0.940000,0.523891,47,3,3069,3377,44,44
2,fold_1,1,with_meta,0.001089,0.226506,0.856430,0.010753,0.983141,0.983871,0.167763,183,3,2024,408,56,106
3,fold_1,1,without_meta,0.000216,0.246109,0.865667,0.311828,0.934622,0.994624,0.002056,185,1,2427,5,52,52
4,fold_1,2,with_meta,0.000025,0.319577,0.895894,0.387755,0.996088,1.000000,0.007296,49,0,18777,138,69,114
5,fold_1,2,without_meta,0.000020,0.423965,0.886246,0.551020,0.997885,1.000000,0.002643,49,0,18865,50,65,65
6,fold_1,3,with_meta,0.000415,0.526485,0.972044,0.589744,0.997628,1.000000,0.183485,39,0,12736,2862,69,107
7,fold_1,3,without_meta,0.001141,0.428797,0.965397,0.589744,0.989358,1.000000,0.282857,39,0,11186,4412,65,65
8,fold_1,4,with_meta,0.002461,0.006154,0.500000,0.000000,1.000000,1.000000,0.000000,2,0,323,0,25,47
9,fold_1,4,without_meta,0.002461,0.006154,0.500000,0.000000,1.000000,1.000000,0.000000,2,0,323,0,21,21
10,fold_2,0,with_meta,0.000872,0.003980,0.759511,0.000000,1.000000,0.571429,0.761008,8,6,2144,6827,48,82
11,fold_2,0,without_meta,0.000398,0.003991,0.747866,0.000000,1.000000,0.857143,0.604615,12,2,3547,5424,44,44
12,fold_2,1,with_meta,0.000355,0.269309,0.963952,0.075000,0.996763,1.000000,0.310136,80,0,3410,1533,56,110
13,fold_2,1,without_meta,0.000407,0.301342,0.967755,0.275000,0.990087,1.000000,0.222335,80,0,3844,1099,52,52
14,fold_2,2,with_meta,0.000680,0.027572,0.694531,0.000000,0.996897,0.750000,0.328430,24,8,5844,2858,69,114
15,fold_2,2,without_meta,0.000642,0.040825,0.783789,0.000000,0.994369,0.937500,0.251207,30,2,6516,2186,65,65
16,fold_2,3,with_meta,0.013551,0.001788,0.606770,0.000000,0.992617,0.217391,0.830872,5,18,3505,17219,69,107
17,fold_2,3,without_meta,0.011565,0.001827,0.552879,0.000000,0.996478,0.086957,0.822332,2,21,3682,17042,65,65
18,fold_2,4,with_meta,0.003340,0.004298,0.500000,0.000000,1.000000,1.000000,0.000000,3,0,695,0,25,47
19,fold_2,4,without_meta,0.003340,0.004298,0.500000,0.000000,1.000000,1.000000,0.000000,3,0,695,0,21,21
20,fold_3,0,with_meta,0.000062,0.007033,0.912511,0.000000,1.000000,1.000000,0.044534,4,0,11564,539,48,84
21,fold_3,0,without_meta,0.000060,0.001318,0.824135,0.000000,1.000000,1.000000,0.015285,4,0,11918,185,44,44
22,fold_3,1,with_meta,0.000957,0.040131,0.859632,0.080000,0.994859,1.000000,0.168595,25,0,3881,787,56,111
23,fold_3,1,without_meta,0.002007,0.029314,0.830840,0.160000,0.976864,1.000000,0.175878,25,0,3847,821,52,52
24,fold_3,2,with_meta,0.000065,0.024948,0.795067,0.000000,1.000000,1.000000,0.026089,7,0,13663,366,69,115
25,fold_3,2,without_meta,0.000127,0.334078,0.829038,0.285714,0.999929,1.000000,0.022525,7,0,13713,316,65,65
26,fold_3,3,with_meta,0.000225,0.170292,0.892870,0.333333,0.999842,1.000000,0.477269,3,0,6623,6047,69,108
27,fold_3,3,without_meta,0.000078,0.345243,0.875428,0.333333,0.999290,1.000000,0.232991,3,0,9718,2952,65,65
28,fold_3,4,with_meta,0.003684,NaN,NaN,NaN,1.000000,NaN,0.000000,0,0,344,0,25,50
29,fold_3,4,without_meta,0.003684,NaN,NaN,NaN,1.000000,NaN,0.000000,0,0,344,0,21,21

,inspection_type,variant,folds,mean_pr_auc,mean_roc_auc,mean_fixed_recall,mean_thresholded_recall,mean_thresholded_false_call_reduction,mean_encoded_features
0,0,with_meta,3,0.011260,0.814995,0.000000,0.837143,0.495735,82.000000
1,0,without_meta,3,0.006677,0.736893,0.000000,0.932381,0.381264,44.000000
2,1,with_meta,3,0.178649,0.893338,0.055251,0.994624,0.215498,109.000000
3,1,without_meta,3,0.192255,0.888087,0.248943,0.998208,0.133423,52.000000
4,2,with_meta,3,0.124032,0.795164,0.129252,0.916667,0.120605,114.333333
5,2,without_meta,3,0.266289,0.833024,0.278912,0.979167,0.092125,65.000000
6,3,with_meta,3,0.232855,0.823895,0.307692,0.739130,0.497209,107.333333
7,3,without_meta,3,0.258622,0.797901,0.307692,0.695652,0.446060,65.000000
8,4,with_meta,3,0.005226,0.500000,0.000000,1.000000,0.000000,48.000000
9,4,without_meta,3,0.005226,0.500000,0.000000,1.000000,0.000000,21.000000

,selected_variant,mean_pr_auc,mean_thresholded_recall,mean_thresholded_false_call_reduction,mean_encoded_features
inspection_type,,,,,
0,with_meta,0.011260,0.837143,0.495735,82.0
1,without_meta,0.192255,0.998208,0.133423,52.0
2,without_meta,0.266289,0.979167,0.092125,65.0
3,without_meta,0.258622,0.695652,0.446060,65.0
4,with_meta,0.005226,1.000000,0.000000,48.0

2026-08-25 16:31:03,018 | INFO | selected_variant_by_type={0: 'with_meta', 1: 'without_meta', 2: 'without_meta', 3: 'without_meta', 4: 'with_meta'}

               threshold  positive_samples    recall  false_call_reduction  \
fold   scope
fold_1 global   0.000022               200  0.990000              0.008132
       type_0   0.002342                11  1.000000              0.374539
       type_1   0.000216                20  1.000000              0.005977
       type_2   0.000020                92  1.000000              0.005503
       type_3   0.001141                73  1.000000              0.360728
       type_4   0.002461                 4  1.000000              0.000000
fold_2 global   0.000754               326  0.990798              0.361440
       type_0   0.000872                50  1.000000              0.527149
       type_1   0.000407               186  0.994624              0.176398
       type_2   0.000642                49  1.000000              0.379064
       type_3   0.011565                39  1.000000              0.722016
       type_4   0.003340                 2  1.000000              0.000000
fold_3 global   0.000078               152  0.993421              0.102419
       type_0   0.000062                14  1.000000              0.034110
       type_1   0.002007                80  1.000000              0.517904
       type_2   0.000127                32  1.000000              0.081935
       type_3   0.000078                23  1.000000              0.194509
       type_4   0.003684                 3  1.000000              0.000000

                tp  fn
fold   scope
fold_1 global  198   2
       type_0   11   0
       type_1   20   0
       type_2   92   0
       type_3   73   0
       type_4    4   0
fold_2 global  323   3
       type_0   50   0
       type_1  185   1
       type_2   49   0
       type_3   39   0
       type_4    2   0
fold_3 global  151   1
       type_0   14   0
       type_1   80   0
       type_2   32   0
       type_3   23   0
       type_4    3   0

                                 positive_samples    pr_auc  precision  \
fold   strategy
fold_1 fixed_0.5                              326  0.194200   0.228330
       global_threshold                       326  0.194200   0.007421
       type_specific_thresholds               326  0.194200   0.009154
fold_2 fixed_0.5                              152  0.053731   0.113990
       global_threshold                       152  0.053731   0.005296
       type_specific_thresholds               152  0.053731   0.007234
fold_3 fixed_0.5                               39  0.035074   0.056000
       global_threshold                        39  0.035074   0.000976
       type_specific_thresholds                39  0.035074   0.000994

                                   recall  false_call_reduction        f1  \
fold   strategy
fold_1 fixed_0.5                 0.331288              0.991650  0.270338
       global_threshold          1.000000              0.002493  0.014732
       type_specific_thresholds  0.987730              0.202704  0.018140
fold_2 fixed_0.5                 0.144737              0.996117  0.127536
       global_threshold          0.888158              0.424140  0.010528
       type_specific_thresholds  0.809211              0.616646  0.014339
fold_3 fixed_0.5                 0.179487              0.997307  0.085366
       global_threshold          1.000000              0.088762  0.001950
       type_specific_thresholds  1.000000              0.105628  0.001987

                                  tp   fn     fp     tn
fold   strategy
fold_1 fixed_0.5                 108  218    365  43349
       global_threshold          326    0  43605    109
       type_specific_thresholds  322    4  34853   8861
fold_2 fixed_0.5                  22  130    171  43864
       global_threshold          135   17  25358  18677
       type_specific_thresholds  123   29  16881  27154
fold_3 fixed_0.5                   7   32    118  43696
       global_threshold           39    0  39925   3889
       type_specific_thresholds   39    0  39186   4628

                        threshold  positive_samples    pr_auc    recall  \
fold   inspection_type
fold_1 0                 0.002342                50  0.022766  0.940000
       1                 0.000216               186  0.246109  0.994624
       2                 0.000020                49  0.423965  1.000000
       3                 0.001141                39  0.428797  1.000000
       4                 0.002461                 2  0.006154  1.000000
fold_2 0                 0.000872                14  0.003980  0.571429
       1                 0.000407                80  0.301342  1.000000
       2                 0.000642                32  0.040825  0.937500
       3                 0.011565                23  0.001827  0.086957
       4                 0.003340                 3  0.004298  1.000000
fold_3 0                 0.000062                 4  0.007033  1.000000
       1                 0.002007                25  0.029314  1.000000
       2                 0.000127                 7  0.334078  1.000000
       3                 0.000078                 3  0.345243  1.000000
       4                 0.003684                 0       NaN       NaN

                        false_call_reduction   tp  fn
fold   inspection_type
fold_1 0                            0.681663   47   3
       1                            0.002056  185   1
       2                            0.002643   49   0
       3                            0.282857   39   0
       4                            0.000000    2   0
fold_2 0                            0.761008    8   6
       1                            0.222335   80   0
       2                            0.251207   30   2
       3                            0.822332    2  21
       4                            0.000000    3   0
fold_3 0                            0.044534    4   0
       1                            0.175878   25   0
       2                            0.022525    7   0
       3                            0.232991    3   0
       4                            0.000000    0   0

,folds,mean_pr_auc,mean_recall,min_recall,recall_99_folds,mean_false_call_reduction,min_false_call_reduction,total_tp,total_fn
strategy,,,,,,,,,
fixed_0.5,3,0.094335,0.218504,0.144737,0,0.995025,0.991650,137,380
global_threshold,3,0.094335,0.962719,0.888158,2,0.171798,0.002493,500,17
type_specific_thresholds,3,0.094335,0.932314,0.809211,1,0.308326,0.105628,484,33

                                     train_rows  train_positive  \
fold   inspection_type variant
fold_1 0               with_meta          28277              32
                       without_meta       28277              32
       1               with_meta          22698             269
                       without_meta       22698             269
       2               with_meta          42288             408
                       without_meta       42288             408
       3               with_meta          37264             510
                       without_meta       37264             510
       4               with_meta           1610               4
                       without_meta        1610               4
fold_2 0               with_meta          36685              43
                       without_meta       36685              43
       1               with_meta          26566             289
                       without_meta       26566             289
       2               with_meta          58736             500
                       without_meta       58736             500
       3               with_meta          51683             583
                       without_meta       51683             583
       4               with_meta           2446               8
                       without_meta        2446               8
fold_3 0               with_meta          43181              93
                       without_meta       43181              93
       1               with_meta          29184             475
                       without_meta       29184             475
       2               with_meta          77700             549
                       without_meta       77700             549
       3               with_meta          67320             622
                       without_meta       67320             622
       4               with_meta           2771              10
                       without_meta        2771              10

                                     calibration_rows  evaluation_rows  \
fold   inspection_type variant
fold_1 0               with_meta                 8408             6496
                       without_meta              8408             6496
       1               with_meta                 3868             2618
                       without_meta              3868             2618
       2               with_meta                16448            18964
                       without_meta             16448            18964
       3               with_meta                14419            15637
                       without_meta             14419            15637
       4               with_meta                  836              325
                       without_meta               836              325
fold_2 0               with_meta                 6496             8985
                       without_meta              6496             8985
       1               with_meta                 2618             5023
                       without_meta              2618             5023
       2               with_meta                18964             8734
                       without_meta             18964             8734
       3               with_meta                15637            20747
                       without_meta             15637            20747
       4               with_meta                  325              698
                       without_meta               325              698
fold_3 0               with_meta                 8985            12107
                       without_meta              8985            12107
       1               with_meta                 5023             4693
                       without_meta              5023             4693
       2               with_meta                 8734            14036
                       without_meta              8734            14036
       3               with_meta                20747            12673
                       without_meta             20747            12673
       4               with_meta                  698              344
                       without_meta               698              344

                                     raw_features  encoded_features
fold   inspection_type variant
fold_1 0               with_meta               48                80
                       without_meta            44                44
       1               with_meta               56               106
                       without_meta            52                52
       2               with_meta               69               114
                       without_meta            65                65
       3               with_meta               69               107
                       without_meta            65                65
       4               with_meta               25                47
                       without_meta            21                21
fold_2 0               with_meta               48                82
                       without_meta            44                44
       1               with_meta               56               110
                       without_meta            52                52
       2               with_meta               69               114
                       without_meta            65                65
       3               with_meta               69               107
                       without_meta            65                65
       4               with_meta               25                47
                       without_meta            21                21
fold_3 0               with_meta               48                84
                       without_meta            44                44
       1               with_meta               56               111
                       without_meta            52                52
       2               with_meta               69               115
                       without_meta            65                65
       3               with_meta               69               108
                       without_meta            65                65
       4               with_meta               25                50
                       without_meta            21                21

2026-08-25 16:31:03,832 | INFO | walk_forward_strategy_summary={'fixed_0.5': {'folds': 3, 'mean_pr_auc': 0.0943351068729958, 'mean_recall': 0.21850412171690828, 'min_recall': 0.14473684210526316, 'recall_99_folds': 0, 'mean_false_call_reduction': 0.995024598156784, 'min_false_call_reduction': 0.9916502722240015, 'total_tp': 137, 'total_fn': 380}, 'global_threshold': {'folds': 3, 'mean_pr_auc': 0.0943351068729958, 'mean_recall': 0.962719298245614, 'min_recall': 0.8881578947368421, 'recall_99_folds': 2, 'mean_false_call_reduction': 0.17179831737668902, 'min_false_call_reduction': 0.0024934803495447683, 'total_tp': 500, 'total_fn': 17}, 'type_specific_thresholds': {'folds': 3, 'mean_pr_auc': 0.0943351068729958, 'mean_recall': 0.9323135292218275, 'min_recall': 0.8092105263157895, 'recall_99_folds': 1, 'mean_false_call_reduction': 0.30832604236924255, 'min_false_call_reduction': 0.1056283379741635, 'total_tp': 484, 'total_fn': 33}}

2026-08-25 16:31:04,888 | INFO | validation_fit_done type=0 variant=with_meta

2026-08-25 16:31:06,246 | INFO | validation_fit_done type=1 variant=without_meta

2026-08-25 16:31:08,115 | INFO | validation_fit_done type=2 variant=without_meta

2026-08-25 16:31:09,879 | INFO | validation_fit_done type=3 variant=without_meta

2026-08-25 16:31:10,020 | INFO | validation_fit_done type=4 variant=with_meta

rows                    44026.000000
positive_samples          357.000000
tn                      43597.000000
fp                         72.000000
fn                        227.000000
tp                        130.000000
accuracy                    0.993209
precision                   0.643564
recall                      0.364146
false_call_reduction        0.998351
f1                          0.465116
roc_auc                     0.951161
pr_auc                      0.471722
Name: type_expert_validation, dtype: float64

,rows,positive_samples,pr_auc,roc_auc,accuracy,precision,recall,false_call_reduction,f1,tp,fn,fp,tn
inspection_type,,,,,,,,,,,,,
0,13289,12,0.004690,0.863599,0.999097,0.000000,0.000000,1.000000,0.000000,0,12,0,13277
1,6422,224,0.697741,0.968575,0.975553,0.679144,0.566964,0.990319,0.618005,127,97,60,6138
2,7161,27,0.323275,0.938749,0.996230,0.500000,0.074074,0.999720,0.129032,2,25,2,7132
3,16252,21,0.071857,0.914731,0.998154,0.090909,0.047619,0.999384,0.062500,1,20,10,16221
4,902,73,0.080931,0.500000,0.919069,0.000000,0.000000,1.000000,0.000000,0,73,0,829

,selected_variant,train_rows,train_positive,validation_rows,validation_positive,raw_features,encoded_features,trees
inspection_type,,,,,,,,
0,with_meta,64273,111,13289,12,48,88,400
1,without_meta,38900,580,6422,224,52,52,400
2,without_meta,100470,588,7161,27,65,65,400
3,without_meta,100740,648,16252,21,65,65,400
4,with_meta,3813,13,902,73,25,53,400

,threshold,positive_samples,recall,false_call_reduction,tp,fn,fp,tn
scope,,,,,,,,
global,0.000603,357,0.991597,0.626463,354,3,16312,27357
0,0.000231,12,1.000000,0.498682,12,0,6656,6621
1,0.001392,224,0.991071,0.618748,222,2,2363,3835
2,0.000209,27,1.000000,0.348893,27,0,4645,2489
3,0.000283,21,1.000000,0.522026,21,0,7758,8473
4,0.003448,73,1.000000,0.000000,73,0,829,0

,pr_auc,precision,recall,false_call_reduction,f1,tp,fn,fp,tn
fixed_0.5,0.471722,0.643564,0.364146,0.998351,0.465116,130.0,227.0,72.0,43597.0
global_threshold,0.471722,0.021241,0.991597,0.626463,0.041591,354.0,3.0,16312.0,27357.0
type_specific_thresholds,0.471722,0.015704,0.994398,0.490462,0.030919,355.0,2.0,22251.0,21418.0

2026-08-25 16:31:10,267 | INFO | validation_strategy_metrics={'fixed_0.5': {'rows': 44026.0, 'positive_samples': 357.0, 'tn': 43597.0, 'fp': 72.0, 'fn': 227.0, 'tp': 130.0, 'accuracy': 0.9932085585790215, 'precision': 0.6435643564356436, 'recall': 0.3641456582633053, 'false_call_reduction': 0.9983512331402139, 'f1': 0.46511627906976744, 'roc_auc': 0.9511612472051496, 'pr_auc': 0.471722425482273}, 'global_threshold': {'rows': 44026.0, 'positive_samples': 357.0, 'tn': 27357.0, 'fp': 16312.0, 'fn': 3.0, 'tp': 354.0, 'accuracy': 0.6294235224639986, 'precision': 0.02124084963398536, 'recall': 0.9915966386554622, 'false_call_reduction': 0.6264627080995672, 'f1': 0.041590788932620575, 'roc_auc': 0.9511612472051496, 'pr_auc': 0.471722425482273}, 'type_specific_thresholds': {'rows': 44026.0, 'positive_samples': 357.0, 'tn': 21418.0, 'fp': 22251.0, 'fn': 2.0, 'tp': 355.0, 'accuracy': 0.4945486757824922, 'precision': 0.015703795452534725, 'recall': 0.9943977591036415, 'false_call_reduction': 0.4904623417069317, 'f1': 0.030919304968862953, 'roc_auc': 0.9511612472051496, 'pr_auc': 0.471722425482273}}

## 5. 원본 무결성과 결론

실행 전후 원본 해시가 같은지 확인하고, 004 대비 핵심 변화만 요약합니다.

In [5]:
DATA_SHA256_AFTER = sha256_file(DATA_PATH)
MAPPING_SHA256_AFTER = sha256_file(MAPPING_PATH)
assert DATA_SHA256_AFTER == DATA_SHA256_BEFORE
assert MAPPING_SHA256_AFTER == MAPPING_SHA256_BEFORE

verification = pd.Series(
    {
        "dataset_sha256_unchanged": True,
        "mapping_sha256_unchanged": True,
        "test_holdout_used_for_selection": False,
        "test_holdout_predicted": False,
        "fixed_threshold": DECISION_THRESHOLD,
        "global_threshold": global_threshold_selection["threshold"],
        "type_thresholds": thresholds_by_type,
        "log_file": f"docs/peace/{LOG_PATH.name}",
    },
    name="verification",
)
display(verification)

baseline_walk_global = BASELINE_004_WALK["global_threshold"]
baseline_validation_global = BASELINE_004_VALIDATION["global_threshold"]
experiment_specific_summary = {
    "engineered_features": ENGINEERED_FEATURES if "ENGINEERED_FEATURES" in globals() else None,
}
if "selected_variant_by_type" in globals():
    experiment_specific_summary["selected_variant_by_type"] = selected_variant_by_type
if "walk_forward_feature_stats_summary" in globals():
    experiment_specific_summary["feature_stat_rows"] = int(len(walk_forward_feature_stats_summary))
if "validation_feature_stats" in globals():
    experiment_specific_summary["validation_feature_stat_rows"] = int(len(validation_feature_stats))

result_summary = {
    "experiment_id": EXPERIMENT_ID,
    "notebook_path": f"notebooks/{EXPERIMENT_ID}.ipynb",
    "log_path": f"docs/peace/{LOG_PATH.name}",
    "evaluation_scope": "walk_forward_and_validation_only",
    "baseline_004_reference": {
        "walk_forward": BASELINE_004_WALK,
        "validation": BASELINE_004_VALIDATION,
    },
    "walk_forward_strategy_summary": to_builtin_dict(walk_forward_strategy_summary.to_dict(orient="index")),
    "validation_strategy_metrics": to_builtin_dict(validation_strategy_metrics.to_dict(orient="index")),
    "threshold_summary": to_builtin_dict(threshold_summary.reset_index().to_dict(orient="records")),
    "experiment_specific_summary": to_builtin_dict(experiment_specific_summary),
}
if "selected_variant_summary" in globals():
    result_summary["selected_variant_summary"] = to_builtin_dict(selected_variant_summary.reset_index().to_dict(orient="records"))
if "variant_summary" in globals():
    result_summary["variant_summary"] = to_builtin_dict(variant_summary.to_dict(orient="records"))

logger.info("result_summary_json=%s", json.dumps(result_summary, ensure_ascii=False, sort_keys=True))
logger.info("source_integrity=PASS test_holdout_predicted=False global_threshold=%.8f", global_threshold_selection["threshold"])
logger.info("experiment_complete=%s", EXPERIMENT_ID)
for handler in logger.handlers:
    handler.flush()

global_walk = walk_forward_strategy_summary.loc["global_threshold"]
global_valid = validation_strategy_metrics.loc["global_threshold"]
type_walk = walk_forward_strategy_summary.loc["type_specific_thresholds"]
type_valid = validation_strategy_metrics.loc["type_specific_thresholds"]

conclusion_lines = [
    f"# {{EXPERIMENT_ID}} 결론",
    "",
    f"- Walk-forward 공통 임계값 평균 Recall은 {{global_walk['mean_recall']:.4f}}, 평균 FCR은 {{global_walk['mean_false_call_reduction']:.4f}}이다.",
    f"- 004 대비 공통 임계값 평균 Recall 변화는 {{global_walk['mean_recall'] - baseline_walk_global['mean_recall']:+.4f}}, 평균 FCR 변화는 {{global_walk['mean_false_call_reduction'] - baseline_walk_global['mean_false_call_reduction']:+.4f}}이다.",
    f"- Validation 공통 임계값 Recall은 {{global_valid['recall']:.4f}}, FCR은 {{global_valid['false_call_reduction']:.4f}}이다.",
    f"- 004 대비 Validation 공통 임계값 Recall 변화는 {{global_valid['recall'] - baseline_validation_global['recall']:+.4f}}, FCR 변화는 {{global_valid['false_call_reduction'] - baseline_validation_global['false_call_reduction']:+.4f}}이다.",
    f"- 타입별 임계값 Walk-forward 평균 Recall/FCR은 {{type_walk['mean_recall']:.4f}} / {{type_walk['mean_false_call_reduction']:.4f}}이다.",
    f"- 타입별 임계값 Validation Recall/FCR은 {{type_valid['recall']:.4f}} / {{type_valid['false_call_reduction']:.4f}}이다.",
    "- 이 노트북은 최종 모델 선택 전 후보 비교용이며 80~100% Test는 추론하지 않았다.",
]
if "selected_variant_by_type" in globals():
    variant_text = ", ".join(f"type {{k}}={{v}}" for k, v in selected_variant_by_type.items())
    conclusion_lines.append(f"- 선택된 meta 제거 설정: {{variant_text}}")
if "ENGINEERED_FEATURES" in globals():
    conclusion_lines.append(f"- 추가된 파생 변수: {{', '.join(ENGINEERED_FEATURES)}}")

display(Markdown("\n".join(conclusion_lines)))

dataset_sha256_unchanged                                                        True
mapping_sha256_unchanged                                                        True
test_holdout_used_for_selection                                                False
test_holdout_predicted                                                         False
fixed_threshold                                                                  0.5
global_threshold                                                            0.000603
type_thresholds                    {0: 0.00023106035951059312, 1: 0.0013922951184...
log_file                           docs/peace/0825_peace_017_type_expert_typewise...
Name: verification, dtype: object

2026-08-25 16:31:10,470 | INFO | result_summary_json={"baseline_004_reference": {"validation": {"fixed_0.5": {"false_call_reduction": 0.995809384231377, "fn": 206, "fp": 183, "pr_auc": 0.4496564930298315, "recall": 0.42296918767507, "tn": 43486, "tp": 151}, "global_threshold": {"false_call_reduction": 0.6993977421053836, "fn": 3, "fp": 13127, "pr_auc": 0.4496564930298315, "recall": 0.9915966386554622, "tn": 30542, "tp": 354}, "type_specific_thresholds": {"false_call_reduction": 0.5644965536192722, "fn": 2, "fp": 19018, "pr_auc": 0.4496564930298315, "recall": 0.9943977591036415, "tn": 24651, "tp": 355}}, "walk_forward": {"fixed_0.5": {"mean_false_call_reduction": 0.997159476859665, "mean_pr_auc": 0.06456566580859706, "mean_recall": 0.08378869542899249, "min_recall": 0.039473684210526314, "recall_99_folds": 0}, "global_threshold": {"mean_false_call_reduction": 0.16944884398683502, "mean_pr_auc": 0.06456566580859706, "mean_recall": 0.9692982456140351, "min_recall": 0.9078947368421053, "recall_99_folds": 2}, "type_specific_thresholds": {"mean_false_call_reduction": 0.33363103162699187, "mean_pr_auc": 0.06456566580859706, "mean_recall": 0.9236895920783553, "min_recall": 0.7894736842105263, "recall_99_folds": 1}}}, "evaluation_scope": "walk_forward_and_validation_only", "experiment_id": "0825_peace_017_type_expert_typewise_meta_removal", "experiment_specific_summary": {"engineered_features": null, "selected_variant_by_type": {"0": "with_meta", "1": "without_meta", "2": "without_meta", "3": "without_meta", "4": "with_meta"}}, "log_path": "docs/peace/0825_peace_017_type_expert_typewise_meta_removal.log", "notebook_path": "notebooks/0825_peace_017_type_expert_typewise_meta_removal.ipynb", "selected_variant_summary": [{"inspection_type": 0, "mean_encoded_features": 82.0, "mean_pr_auc": 0.011259669139525552, "mean_thresholded_false_call_reduction": 0.4957350504188181, "mean_thresholded_recall": 0.8371428571428572, "selected_variant": "with_meta"}, {"inspection_type": 1, "mean_encoded_features": 52.0, "mean_pr_auc": 0.19225521048346952, "mean_thresholded_false_call_reduction": 0.13342295204633625, "mean_thresholded_recall": 0.9982078853046595, "selected_variant": "without_meta"}, {"inspection_type": 2, "mean_encoded_features": 65.0, "mean_pr_auc": 0.26628932244067277, "mean_thresholded_false_call_reduction": 0.09212493133076895, "mean_thresholded_recall": 0.9791666666666666, "selected_variant": "without_meta"}, {"inspection_type": 3, "mean_encoded_features": 65.0, "mean_pr_auc": 0.25862203137278855, "mean_thresholded_false_call_reduction": 0.44605989693364884, "mean_thresholded_recall": 0.6956521739130435, "selected_variant": "without_meta"}, {"inspection_type": 4, "mean_encoded_features": 48.0, "mean_pr_auc": 0.005225920211593564, "mean_thresholded_false_call_reduction": 0.0, "mean_thresholded_recall": 1.0, "selected_variant": "with_meta"}], "threshold_summary": [{"accuracy": 0.6294235224639986, "f1": 0.041590788932620575, "false_call_reduction": 0.6264627080995672, "fn": 3, "fp": 16312, "min_recall": 0.99, "positive_samples": 357, "pr_auc": 0.471722425482273, "precision": 0.02124084963398536, "recall": 0.9915966386554622, "roc_auc": 0.9511612472051496, "rows": 44026, "scope": "global", "threshold": 0.0006029532523825765, "tn": 27357, "tp": 354}, {"accuracy": 0.4991346226202122, "f1": 0.003592814371257485, "false_call_reduction": 0.4986819311591474, "fn": 0, "fp": 6656, "min_recall": 0.99, "positive_samples": 12, "pr_auc": 0.004690380246653749, "precision": 0.001799640071985603, "recall": 1.0, "roc_auc": 0.863598704526625, "rows": 13289, "scope": 0, "threshold": 0.00023106035951059312, "tn": 6621, "tp": 12}, {"accuracy": 0.6317346620990346, "f1": 0.15806336774652902, "false_call_reduction": 0.6187479832203937, "fn": 2, "fp": 2363, "min_recall": 0.99, "positive_samples": 224, "pr_auc": 0.6977405336261363, "precision": 0.08588007736943908, "recall": 0.9910714285714286, "roc_auc": 0.9685753324805237, "rows": 6422, "scope": 1, "threshold": 0.0013922951184213161, "tn": 3835, "tp": 222}, {"accuracy": 0.35134757715402876, "f1": 0.011491806767397318, "false_call_reduction": 0.34889262685730305, "fn": 0, "fp": 4645, "min_recall": 0.99, "positive_samples": 27, "pr_auc": 0.3232746698045354, "precision": 0.005779109589041096, "recall": 1.0, "roc_auc": 0.9387492342356374, "rows": 7161, "scope": 2, "threshold": 0.000208851823117584, "tn": 2489, "tp": 27}, {"accuracy": 0.5226433669702191, "f1": 0.005384615384615384, "false_call_reduction": 0.5220257531883433, "fn": 0, "fp": 7758, "min_recall": 0.99, "positive_samples": 21, "pr_auc": 0.07185747110011825, "precision": 0.002699575780948708, "recall": 1.0, "roc_auc": 0.9147310701743576, "rows": 16252, "scope": 3, "threshold": 0.0002832834143191576, "tn": 8473, "tp": 21}, {"accuracy": 0.08093126385809313, "f1": 0.14974358974358976, "false_call_reduction": 0.0, "fn": 0, "fp": 829, "min_recall": 0.99, "positive_samples": 73, "pr_auc": 0.08093126385809313, "precision": 0.08093126385809313, "recall": 1.0, "roc_auc": 0.5, "rows": 902, "scope": 4, "threshold": 0.0034481300972402096, "tn": 0, "tp": 73}], "validation_strategy_metrics": {"fixed_0.5": {"accuracy": 0.9932085585790215, "f1": 0.46511627906976744, "false_call_reduction": 0.9983512331402139, "fn": 227.0, "fp": 72.0, "positive_samples": 357.0, "pr_auc": 0.471722425482273, "precision": 0.6435643564356436, "recall": 0.3641456582633053, "roc_auc": 0.9511612472051496, "rows": 44026.0, "tn": 43597.0, "tp": 130.0}, "global_threshold": {"accuracy": 0.6294235224639986, "f1": 0.041590788932620575, "false_call_reduction": 0.6264627080995672, "fn": 3.0, "fp": 16312.0, "positive_samples": 357.0, "pr_auc": 0.471722425482273, "precision": 0.02124084963398536, "recall": 0.9915966386554622, "roc_auc": 0.9511612472051496, "rows": 44026.0, "tn": 27357.0, "tp": 354.0}, "type_specific_thresholds": {"accuracy": 0.4945486757824922, "f1": 0.030919304968862953, "false_call_reduction": 0.4904623417069317, "fn": 2.0, "fp": 22251.0, "positive_samples": 357.0, "pr_auc": 0.471722425482273, "precision": 0.015703795452534725, "recall": 0.9943977591036415, "roc_auc": 0.9511612472051496, "rows": 44026.0, "tn": 21418.0, "tp": 355.0}}, "variant_summary": [{"folds": 3, "inspection_type": 0, "mean_encoded_features": 82.0, "mean_fixed_recall": 0.0, "mean_pr_auc": 0.011259669139525552, "mean_roc_auc": 0.8149950811178862, "mean_thresholded_false_call_reduction": 0.4957350504188181, "mean_thresholded_recall": 0.8371428571428572, "variant": "with_meta"}, {"folds": 3, "inspection_type": 0, "mean_encoded_features": 44.0, "mean_fixed_recall": 0.0, "mean_pr_auc": 0.006676865325309064, "mean_roc_auc": 0.7368929674280795, "mean_thresholded_false_call_reduction": 0.3812637071777765, "mean_thresholded_recall": 0.9323809523809524, "variant": "without_meta"}, {"folds": 3, "inspection_type": 1, "mean_encoded_features": 109.0, "mean_fixed_recall": 0.055250896057347676, "mean_pr_auc": 0.1786488105929386, "mean_roc_auc": 0.8933378239943212, "mean_thresholded_false_call_reduction": 0.21549779678080414, "mean_thresholded_recall": 0.9946236559139785, "variant": "with_meta"}, {"folds": 3, "inspection_type": 1, "mean_encoded_features": 52.0, "mean_fixed_recall": 0.2489426523297491, "mean_pr_auc": 0.19225521048346952, "mean_roc_auc": 0.8880870755169129, "mean_thresholded_false_call_reduction": 0.13342295204633625, "mean_thresholded_recall": 0.9982078853046595, "variant": "without_meta"}, {"folds": 3, "inspection_type": 2, "mean_encoded_features": 114.33333333333333, "mean_fixed_recall": 0.1292517006802721, "mean_pr_auc": 0.12403234704072748, "mean_roc_auc": 0.7951642937351017, "mean_thresholded_false_call_reduction": 0.12060495297698236, "mean_thresholded_recall": 0.9166666666666666, "variant": "with_meta"}, {"folds": 3, "inspection_type": 2, "mean_encoded_features": 65.0, "mean_fixed_recall": 0.2789115646258503, "mean_pr_auc": 0.26628932244067277, "mean_roc_auc": 0.833024133758439, "mean_thresholded_false_call_reduction": 0.09212493133076895, "mean_thresholded_recall": 0.9791666666666666, "variant": "without_meta"}, {"folds": 3, "inspection_type": 3, "mean_encoded_features": 107.33333333333333, "mean_fixed_recall": 0.3076923076923077, "mean_pr_auc": 0.23285482122996992, "mean_roc_auc": 0.8238948089230426, "mean_thresholded_false_call_reduction": 0.49720887344652503, "mean_thresholded_recall": 0.7391304347826088, "variant": "with_meta"}, {"folds": 3, "inspection_type": 3, "mean_encoded_features": 65.0, "mean_fixed_recall": 0.3076923076923077, "mean_pr_auc": 0.25862203137278855, "mean_roc_auc": 0.7979011280378533, "mean_thresholded_false_call_reduction": 0.44605989693364884, "mean_thresholded_recall": 0.6956521739130435, "variant": "without_meta"}, {"folds": 3, "inspection_type": 4, "mean_encoded_features": 48.0, "mean_fixed_recall": 0.0, "mean_pr_auc": 0.005225920211593564, "mean_roc_auc": 0.5, "mean_thresholded_false_call_reduction": 0.0, "mean_thresholded_recall": 1.0, "variant": "with_meta"}, {"folds": 3, "inspection_type": 4, "mean_encoded_features": 21.0, "mean_fixed_recall": 0.0, "mean_pr_auc": 0.005225920211593564, "mean_roc_auc": 0.5, "mean_thresholded_false_call_reduction": 0.0, "mean_thresholded_recall": 1.0, "variant": "without_meta"}], "walk_forward_strategy_summary": {"fixed_0.5": {"folds": 3, "mean_false_call_reduction": 0.995024598156784, "mean_pr_auc": 0.0943351068729958, "mean_recall": 0.21850412171690828, "min_false_call_reduction": 0.9916502722240015, "min_recall": 0.14473684210526316, "recall_99_folds": 0, "total_fn": 380, "total_tp": 137}, "global_threshold": {"folds": 3, "mean_false_call_reduction": 0.17179831737668902, "mean_pr_auc": 0.0943351068729958, "mean_recall": 0.962719298245614, "min_false_call_reduction": 0.0024934803495447683, "min_recall": 0.8881578947368421, "recall_99_folds": 2, "total_fn": 17, "total_tp": 500}, "type_specific_thresholds": {"folds": 3, "mean_false_call_reduction": 0.30832604236924255, "mean_pr_auc": 0.0943351068729958, "mean_recall": 0.9323135292218275, "min_false_call_reduction": 0.1056283379741635, "min_recall": 0.8092105263157895, "recall_99_folds": 1, "total_fn": 33, "total_tp": 484}}}

2026-08-25 16:31:10,471 | INFO | source_integrity=PASS test_holdout_predicted=False global_threshold=0.00060295

2026-08-25 16:31:10,471 | INFO | experiment_complete=0825_peace_017_type_expert_typewise_meta_removal

# {EXPERIMENT_ID} 결론

- Walk-forward 공통 임계값 평균 Recall은 {global_walk['mean_recall']:.4f}, 평균 FCR은 {global_walk['mean_false_call_reduction']:.4f}이다.
- 004 대비 공통 임계값 평균 Recall 변화는 {global_walk['mean_recall'] - baseline_walk_global['mean_recall']:+.4f}, 평균 FCR 변화는 {global_walk['mean_false_call_reduction'] - baseline_walk_global['mean_false_call_reduction']:+.4f}이다.
- Validation 공통 임계값 Recall은 {global_valid['recall']:.4f}, FCR은 {global_valid['false_call_reduction']:.4f}이다.
- 004 대비 Validation 공통 임계값 Recall 변화는 {global_valid['recall'] - baseline_validation_global['recall']:+.4f}, FCR 변화는 {global_valid['false_call_reduction'] - baseline_validation_global['false_call_reduction']:+.4f}이다.
- 타입별 임계값 Walk-forward 평균 Recall/FCR은 {type_walk['mean_recall']:.4f} / {type_walk['mean_false_call_reduction']:.4f}이다.
- 타입별 임계값 Validation Recall/FCR은 {type_valid['recall']:.4f} / {type_valid['false_call_reduction']:.4f}이다.
- 이 노트북은 최종 모델 선택 전 후보 비교용이며 80~100% Test는 추론하지 않았다.
- 선택된 meta 제거 설정: {variant_text}